### ISSUE TITLE
time_of_day comparison operators

### ISSUE THREAD

**Issue by ethortdev** [HowardHinnant/date#100]
Hello. Thanks for the great library. I noticed that time_of_day did not have comparison operators (==, !=, etc). Is there a plan to add these, or are they purposefully not included? What might be the reason to not include these?

**Comment by HowardHinnant** [comment]
`time_of_day` is more of a formatter than a storage type.  And because of the `make12()` and `make24()` formatting options on this type, the semantics of comparison are not obvious.  Should two values be equal if they represent the same time, but one is in 12-hour mode and the other in 24-hour mode?

Instead of making a decision on a question like that and then having half of my customers get bitten by assuming differently, I opted to not provide such operators at all.  However, given any two `time_of_day<D1> x` and `time_of_day<D2> y`, one could compare them with `x.to_duration() == y.to_duration()`.  And now the answer to my question about formatting mode is immediately explicit (mode is not taken into account).  With the advent of lambdas, customizing such comparisons for generic algorithms is not burdensome either.

If one wanted to compare taking `mode()` into account, you could do that too given that there are getters for each field including `mode()`.

**Comment by ethortdev** [comment]
Thanks for the detailed and timely explanation!

**Comment by HowardHinnant** [comment]
I did find one place in the tz implementation that I'm not using `time_of_day` for formatting:

https://github.com/HowardHinnant/date/blob/master/tz.cpp#L789-L800

Here I actually do need to store hours/minutes/seconds fields.  But I built a custom type to do that and used `time_of_day` to help out with the conversion from a `time_point`.

One of the motivating goals for tz was to stress the date.h API and find out what was missing. :-)
