### ISSUE TITLE
A way to get first weekday in current locale

### ISSUE THREAD

**Issue by danielrempel** [HowardHinnant/date#101]
I'm not sure but maybe the library should have a way of determining the first day of week in current locale?

Or is it too ugly or non-portable and thus not implemented?

**Comment by HowardHinnant** [comment]
That information does not appear in C++ locales, nor in the IANA database.  Thus it is not exposed here for lack of a credible source to draw on.

Fwiw, here is a way to use this library to print out yearly calendars in an extremely flexible manner, including being able to specify the first day of the week:

http://stackoverflow.com/a/40097700/576911

Additionally the "iso_week" library uses the encoding [1, 7] for [Mon, Sun] which is specified by the ISO week-based calendar.

Finally, and I think most important, this library implements `weekday` arithmetic as a circular range.  This enables one to program many date algorithms in an "encoding-independent" manner.  For example, the first Sunday of Nov, 2016 is:
````
sys_days sd = 2016_y/nov/1;
sd += (sun - weekday{sd});
````
I.e. find the first of the month, and then add the  number of days Sunday is past the first of the month.  And this code works whether Sunday is the first day of the week or the last day of the week because `weekday` subtraction always tells you how many days the first operand is past the second operand (always in the range [days{0}, days{6}]).

Of course, `2016_y/nov/sun[1]` is an easier way to write the above, but the above is what is going on under the hood of `2016_y/nov/sun[1]`.
