### ISSUE TITLE
Nearest thing to OADate

### ISSUE THREAD

**Issue by cmaughan** [HowardHinnant/date#123]
In the C# world, you can conveniently convert a Date to an 'OADate' which is a double representing time since a given start date.  Whole units are days, hours are 1/24, mins 1/(24*60), etc.
Is there a similar measure like this in the library?

**Comment by HowardHinnant** [comment]
Yes, I can help you with that.  Would you like that in UTC, the local time zone, or a specifically named time zone?  Or do you need all of the above?

**Comment by HowardHinnant** [comment]
I just looked up `OADate` (I know nothing of C#) and it appears to be a double representing days since the epoch 1899-12-30 00:00:00 UTC.

`chrono::system_clock` doesn't have a specified epoch, but the de facto standard is 1970-01-01 00:00:00 UTC.  You don't even need this library to get the current double of days from this epoch:

    #include <chrono>
    #include <iostream>
    #include <ratio>

    int
    main()
    {
        using namespace std;
        using namespace std::chrono;
        using ddays = duration<double, ratio_multiply<ratio<24>, hours::period>>;
        auto now = time_point_cast<ddays>(system_clock::now());
        cout << std::fixed << now.time_since_epoch().count() << '\n';
    }

This just output for me:

    17201.725601

which is the fractional number of days since 1970-01-01 00:00:00 UTC.  If you would like the fractional number of days from some other epoch or timezone, this library can make that very easy to do (even from `OADate`'s epoch).

**Comment by HowardHinnant** [comment]
It turns out that `TDateTime` uses the same encoding as `OADate`.  Here are conversion functions between `system_clock::time_point` and `TDateTime`:  https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#TDate

**Comment by cmaughan** [comment]
This is just what I needed, thanks a bunch. :)  
FYI; I don't particularly mind about the epoch start time; the important thing is a consistent double for the same date.  I use this when plotting graphs....as a common axis value.  Thanks again ;)

**Comment by HowardHinnant** [comment]
Addressed.
