### ISSUE TITLE
Minor questions and a request

### ISSUE THREAD

**Issue by reesegj** [HowardHinnant/date#148]
Hi Howard,

I've got a few questions of minor importance regarding the date library, and then one request.

Q1 - The library provides the literal suffixes _y and _d. Is there a reason why there's no _m?

Q2 - A year_month_day_last displays as   yyyy/Mon/last .  To get a display of the date without the word "last", I've been casting to a year_month_day before output. Is that the correct or recommended way of printing the date of a year_month_day_last with just numerals?

For example:
constexpr auto a1 = 2015_y/mar/last;
cout << a1 << endl 
<< static_cast<year_month_day>(a1) << endl; // good technique?

Output is:
2015/Mar/last
2015-03-31

Q3 - weekday is the only type whose constructor with an int argument has been explicitly marked as delete. Other types that have valid ranges of arguments that are non-negative or positive, e.g., month, day, don't have the constructor with int deleted. Is there a reason that weekday's constructor is deleted, or that the others aren't?

Q4 - In the documentation in the section "Escape hatch from the conventional syntax" there's the line

constexpr auto x2 = year_month_weekday_last{year{2015}, month{3u}, weekday_last{weekday{0u}}};

If I use month{3} the line still compiles. Is the suffix u in the argument to month superfluous or should compilation really fail if the u is not present?

And now for a strange request:

I'm writing a tutorial on the date library as a series of blog posts. The first post is ready but before I foist it on an unwary public, I thought I would ask you if you can review it. I'm sure you're plenty busy so feel free to decline - I would understand completely. However, if you can squeeze in a quick look let me know and I'll send you a link and password to the post.

Thanks.

Greg Reese

**Comment by HowardHinnant** [comment]
Hi Greg,

> Q1 - The library provides the literal suffixes _y and _d. Is there a reason why there's no _m?

Yes.  I gave it some thought and decided against it.  `3_m` looks too much like "3 meters".  Especially if this library gets standardized, then `3_m` becomes `3m`.  And that would forbid the C++ std::lib from ever developing a units library with meters in it.

Secondly, `mar` is just as good as `3_m`.  I even put `mar` in the `chrono::literals` namespace.

> Q2 - A year_month_day_last displays as yyyy/Mon/last .  ...

Yes, but for readability purposes I like to use "uniform initialization syntax" as opposed to "cast syntax", e.g.:
````
constexpr auto a1 = 2015_y/mar/last;
cout << a1 << '\n' << year_month_day{a1} << endl;
````
`year_month_day_last` is its own type so that you can always add `months` (or `years`) to it, and the result will be `ok()`.  Whereas `jan/31/2017 + months{1}` results in a `!ok()` value.

> Q3 - weekday is the only type whose constructor with an int argument has been explicitly marked as delete. ...

Good question!  I couldn't remember the rationale, so I looked up the commit where I did this and it says:
> Try disabling construction of weekday from int.

This commit was made 2015-09-02 (a year and a half ago), and sounds more like an experiment.  If this is causing you (or others) problems, I would seriously consider reverting it.  The unit tests all pass with it reverted.  If I don't revert it, I need to document a rationale for it.

> Q4 - In the documentation in the section "Escape hatch ...

The `u` suffix looks superfluous to me.  I believe that since the compiler can see that the literal `3` fits within the range of `unsigned`, it's happy.  If I revert the deleted `weekday` constructor, I will change this example.

> I'm writing a tutorial on the date library ...

Awesome!  I would love to review it.

**Comment by reesegj** [comment]
Hi Howard,

Thanks for answering my questions. You can view the post at
https://cppthingsblog.wordpress.com

The password is      Howard

Feel free to send me any comments, questions or criticisms. My email
address is

greg.reese@miamioh.edu

Thanks.
Greg Reese

---------------------------------------------------------------------------------------------------
Greg Reese, Ph.D.
63 Upham Hall
Miami University
Oxford, OH  45056
(513)529-1411 (Voice)
(513)529-3765 (FAX)
greg.reese@miamioh.edu
