### ISSUE TITLE
Question: is it possible to modify the implementation to make it compatible with Excel?

### ISSUE THREAD

**Issue by dibyendumajumdar** [HowardHinnant/date#163]
Hi,

In Excel dates are counted from 1 Jan 1900. I would like to use this date library but my current implementation (derived from Quantlib) is designed to be compatible with Excel. If I wanted to amend the implementation to use 1 Jan 1900 as the first date - is this easy to do? 

Thanks and Regards
Dibyendu

**Comment by HowardHinnant** [comment]
In tz.h there are clocks that have epochs that differ from 1970-01-01.  For example `gps_clock` has an epoch of `1980_y/jan/sun[1]` and `tai_clock` has an epoch of `1958_y/jan/1`.  These clocks interact with `std::chrono::system_clock` by adding/subtracting the difference in their epoch from the `std::chrono::system_clock`: `1970_y/jan/1`.

My advice would be to follow the design of `gps_clock` and `tai_clock` instead of trying to change the epoch of `std::chrono::system_clock`, or the relationship of the calendar types to `system_clock`.  For example, here is the syntax for how to create a `gps_time` from calendar types and chrono durations:
````
#include "tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    using namespace std::chrono_literals;
    auto t = to_gps_time(sys_days{jun/22/2017} + 13h + 4min);
    std::cout << t << '\n';
}
````
Output:
````
2017-06-22 13:04:18
````
And here is how you can implement such things: https://github.com/HowardHinnant/date/blob/master/tz.h#L1411-L1426

Converting to Excel dates will be easier than the `gps_time` conversion because you won't have to deal with the leap second issue.  You'll just need to add/subract the constant `(sys_days{1970_y/jan/1}-sys_days{1900_y/jan/1})`.

**Comment by dibyendumajumdar** [comment]
Thank you - looks like C++ Builder TDate example is similar to what I need to do.

**Comment by dibyendumajumdar** [comment]
Hi - I also had to amend the calculation of weekday to make it consistent with the adjusted serial value.

I am using the algorithms rather than the date.h as latter has stuff that I do not need. I only need the core functions. In my system I am using the value 0 as invalid date - as it plays nicely with Google Protobuf where I can pass dates as integer values. By default the value of an integer is 0 in Protobuf - so having 0 as invalid date is convenient. Of course I can do this because I don't need dates earlier than 1 - which is 31/Dec/1899!
