### ISSUE TITLE
date::parse "%m%d" gives garbage result

### ISSUE THREAD

**Issue by sergeken** [HowardHinnant/date#164]
Parsing the following snipped produces garbage date.  It use to work with older version of date.h.

    string text = "0515";
    date::year_month_day date;
    std::istringstream ss (text);
    ss >> date::parse ("%m%d", date);

**Comment by HowardHinnant** [comment]
Correct, sorry about that.

The error checking on parsing has been tightened up in an effort to eliminate ambiguities and garbage results.  In this example `ss.fail()` is true after the parse, indicating that the value of `date` has not been changed by the `parse`.  The reason the parse failed is because a valid year was not parsed.

However you can still parse partial dates like this.  Just change `date` to have type `month_day`, and it will parse as you expect.  You can then subsequently combine that `month_day` with a `year` to form a full date if desired.  For example:

````
#include "date.h"
#include <iostream>
#include <string>

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;
    string text = "0515";
    month_day md;
    istringstream ss (text);
    ss >> parse ("%m%d", md);
    if (ss.fail())
    {
        cout << "fail\n";
        return 1;
    }
    cout << "md = " << md << '\n';
    auto ymd = md/2017;
    cout << "ymd = " << ymd << '\n';
}
````
Output:
````
md = May/15
ymd = 2017-05-15
````

**Comment by sergeken** [comment]
This is exactly the behavior that I need.  I must admit I've been lazy not to check fail() and not having re-read the documentation, if this was documented.

**Comment by HowardHinnant** [comment]
I've attempted to document it, but the documentation not be good enough.  I'm open to suggestions on it.  And no problem reporting the issue.  It is still valuable feedback for me.  Thanks!
