### ISSUE TITLE
What is the recommended way to format the seconds without the decimal part?

### ISSUE THREAD

**Issue by akimd** [HowardHinnant/date#180]
I do this:
```c++
            if (this->time_microsec())
              return date::format("%Y-%m-%d %H:%M:%S: ", msg.time);
            else
            {
              auto t = std::chrono::time_point_cast<std::chrono::seconds>(msg.time);
              return date::format("%Y-%m-%d %H:%M:%S: ", t);
            }
```
but it's a bit heavy.  Unfortunately, I can't factor with `?:`, as then the output has a more-than-seconds precision, and gets printed with `.000000`.  Is there a better way?  Would you accept an alternative to `%S` that does not include the decimal part?  Or `%.0S`?

Thanks for this great library!

**Comment by HowardHinnant** [comment]
I'm big fan of function-local using namespace directives, especially when dealing with `std::chrono`.  Also use of `floor` instead of `time_point_cast` allows this code to work correctly with dates prior to 1970-01-01, and is easier to read & write for bonus points.  `time_point_cast` rounds towards zero, where `floor` rounds towards negative infinity.

Also `"%F"` is a nice shortcut for `"%Y-%m-%d"`, and `"%T"` is a shortcut for `"%H:%M:%S"`.

So I would code it like this:
````
            using namespace date;
            using namespace std::chrono;
            if (this->time_microsec())
              return date::format("%F %T: ", msg.time);
            return date::format("%F %T: ", floor<seconds>(msg.time));
````

**Comment by akimd** [comment]
Actually I tried with floor and had the result with `.000000`.  But that's because I used `?:` and everything resulted in a single type, with the best precision.  I'm a big fan of `?:` over `if` :)

Thanks for the answer.
