### ISSUE TITLE
Problem parsing times from "America/Indiana/Indianapolis"

### ISSUE THREAD

**Issue by neuraleskimo** [HowardHinnant/date#206]
First, let me say that I am not an expert with time. I suspect the following is due to my misunderstanding...

Background: I am working with historical data collected over 10+ years. Until recently, Indiana (in the Eastern Timezone) did not observe daylight savings time. (I know. I know.) When importing data with tz set to "America/Indiana/Indianapolis", the output of the following code snippet surprised me.

Code snippet:
```
        // In most of Indiana is in the Eastern Timezone, but did not observe
        // daylight savings time until a few years ago
        auto t = date::sys_days(2000_y/6/1) + 12h;
        auto t1 = date::make_zoned("America/New_York", t);
        auto t2 = date::make_zoned("America/Indiana/Indianapolis", t);

        // Simulate reading historical data from disk.
        std::stringstream ss;
        ss << t1;
        date::sys_time<std::chrono::seconds> t3;
        ss >> date::parse("%F %T %Z", t3);  // not UTC
        ss << t2;
        date::sys_time<std::chrono::seconds> t4;
        ss >> date::parse("%F %T %Z", t4);  // while an otherwise valid time,
                                            // the result is 1970-01-01 00:00:00.

        std::cout << "    New York " << t1 << " --> "
                  << date::format("%F %T %Z", t3) << std::endl;
        std::cout << "Indianapolis " << t2 << " --> "
                  << date::format("%F %T %Z", t4) << std::endl;
        std::cout << std::endl;
        std::cout << "    New York " << t1 << " --> "
                  << date::make_zoned("America/New_York", t3) << std::endl;
        std::cout << "Indianapolis " << t2 << " --> "
                  << date::make_zoned("America/Indiana/Indianapolis", t4) << std::endl;
```

Actual output:
```
    New York 2000-06-01 08:00:00 EDT --> 2000-06-01 08:00:00 UTC
Indianapolis 2000-06-01 07:00:00 EST --> 1970-01-01 00:00:00 UTC

    New York 2000-06-01 08:00:00 EDT --> 2000-06-01 04:00:00 EDT
Indianapolis 2000-06-01 07:00:00 EST --> 1969-12-31 19:00:00 EST
```
I expected to get back the original time.

By the way, I tried the same thing with QDateTime and found that Qt imports both cases as if my timezone was set to "America/New_York".

**Comment by neuraleskimo** [comment]
I edited the above a few times to fix formatting problems. Also, left out a comment.

**Comment by HowardHinnant** [comment]
Happy to help.

The first thing I did was insert a print statement for `ss` just before you parse from it the first time:
```
std::cout << "ss = " << ss.str() << '\n';
```
This outputs:
```
ss = 2000-06-01 08:00:00 EDT
```
Which is what I hope you expected (and it is what I expected).

In the next two lines:
```
date::sys_time<std::chrono::seconds> t3;
ss >> date::parse("%F %T %Z", t3);  // not UTC
```
Here's where the problem starts (but all of this can be fixed).

1.  `date::sys_time` _is_ UTC, end of story.

2.  Time zone abbreviations such as EDT are not sufficiently unique that one can reliably identify a time zone with them.  See https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#convert_by_timezone_abbreviation for more information.

3.  `%Z` parses a word, but has no impact on the `time_point` parsed.  But that word parsed from `%Z` can be captured.

In order to recover a time and its time_zone one must output the _name_ of the time_zone, not its abbreviation.  Then you can use `%Z` to recover the name.  Here's how you output the name:
```
    ss << date::format("%F %T ", t1) << t1.get_time_zone()->name();
```
And here is the difference in the result:
```
ss = 2000-06-01 08:00:00 America/New_York
```
To parse that back in you parse into a `local_time` instead of `sys_time`, and you capture the "America/New_York" in a local `std::string`.  Then you can use `make_zoned` with the captured time zone name and the `local_time` to create a new `zoned_time` equivalent to the original:
```
    date::local_time<std::chrono::seconds> t3l;
    std::string t3_time_zone_name;
    ss >> date::parse("%F %T %Z", t3l, t3_time_zone_name);
    auto t3 = date::make_zoned(t3_time_zone_name, t3l);
```
If you like, there's a type alias for `date::local_time<std::chrono::seconds>` called `date::local_seconds`.

The parse puts the "2000-06-01 08:00:00" into `t3l` and "America/New_York" into `t3_time_zone_name`.  Now you just make a new `zoned_time` with `make_zoned` and those two pieces of information.  Then you print out `t1` and `t3`, you'll get:
```
    New York 2000-06-01 08:00:00 EDT --> 2000-06-01 08:00:00 EDT
```
You can do the exact same thing for `t2` and `t4`, but you need to reset `ss` after using it.  First give it a zero string and clear the state flags in it (eofbit is set):
```
    ss.str("");
    ss.clear();
```
Then you're ready to work on `t2` and `t4`.  After making these adjustments, you should get:
```
    New York 2000-06-01 08:00:00 EDT --> 2000-06-01 08:00:00 EDT
Indianapolis 2000-06-01 07:00:00 EST --> 2000-06-01 07:00:00 EST

    New York 2000-06-01 08:00:00 EDT --> 2000-06-01 08:00:00 EDT
Indianapolis 2000-06-01 07:00:00 EST --> 2000-06-01 07:00:00 EST
```
The reason you were getting 1970/1969 is because `ss` just wasn't able to parse because it was shut down with eofbit set.

**Comment by neuraleskimo** [comment]
Sorry for missing resetting the stringstream, missing that the timezone abbreviation has no effect on the timepoint parsed by sys_time(), and wasting your time! Unfortunately, I have no control over the format of the original data. However, I do know where each file was generated, so I can disambiguate the abbreviations using that outside knowledge. Ultimately, I would prefer all data to be UTC regardless of where it was collected for analysis. I wish it had been collected that way. Thanks again!

**Comment by HowardHinnant** [comment]
Not a waste of time at all.  I value the feedback you've given me.  Don't hesitate to ask if you have any more questions.
