### ISSUE TITLE
Parse succeeds on Mac and Windows, fails on Linux

### ISSUE THREAD

**Issue by benjamin-bader** [HowardHinnant/date#207]
I had an intriguing unit test failure today, where a known-good usage of `date::parse` failed when compiled under g++:

(please forgive any obvious mistakes on my part; I'm pretty new to C++, and its sensitivity to different toolchains)

```cpp
const std::string RFC_850 = "%a, %d-%b-%y %H:%M:%S GMT";

time_point tp = {};
std::istringstream input("Sunday, 06-Nov-94 08:49:37 GMT");
input.imbue(std::locale("C"));

input >> date::parse(RFC_850, tp);

if (! input)
{
    // We never hit this on Windows or Mac, which compile using clang.
    // We hit this on Linux, compiled using GCC, but only when ONLY_C_LOCALE is not defined.
    throw std::invalid_argument("fail");
}
```

What's interesting is that the failure went away after I defined `ONLY_C_LOCALE`.  Given that the stream already has the "C" locale, I'm not sure what the problem might be.

For completeness' sake, I observed the failure in the following environment:
Ubuntu 16.04 (trusty)
g++-6

**Comment by HowardHinnant** [comment]
You're doing nothing wrong and everything right. :-)  You've stumbled across two things:

1.  A bug in gcc's `std::time_get`.

2.  The way to work around that bug:  `-DONLY_C_LOCALE`. :-)

The `-DONLY_C_LOCALE` is a flag I created for this lib to not use `std::time_get`, but instead assume the "C" locale is sufficient.  Your `input.imbue(std::locale("C"));` is unnecessary, but harmless.  It is the default anyway, unless you've set the global locale somewhere else, and when you define `ONLY_C_LOCALE`, that setting will be ignored regardless.

I don't have gcc to test this with, but you may also work around it (without `ONLY_C_LOCALE`) by using `%A` in place of `%a`.  They both should be equivalent for parsing, but if I recall, the bug in gcc is that `%a` is expecting the weekday abbreviation instead of the full weekday name.

**Comment by benjamin-bader** [comment]
Thanks for the reply!  Glad to know it's a known and accounted-for issue.

Since this is already worked-around, I'll close this out.
