### ISSUE TITLE
Advice: storing time zones in large data sets

### ISSUE THREAD

**Issue by neuraleskimo** [HowardHinnant/date#208]
I am working with a decent sized set of historical data: > 10 years, ~300GB compressed, and > 10K files. For me (I am not familiar with the intricacies of time on a global-scale),  the problem is that this data has been collected in many time zones and the format differs from year to year. Thanks to Howard, I now have a better understanding of timezone names and abbreviations. 

Here is my dilemma. I can generate a new set of data to:
1) store time zone abbreviations with names (e.g., America/New_York), 
2) store time as UTC and add meta data (e.g., via symbolic links) that carry the time zone info, or
3) store time as UTC.

My inclination is to store time as UTC; however, part of my analysis requires knowledge of the local time. That is, if I find an interesting event, I might want to be able to ask, for example, what was the local time for that even? That is I can't (or shouldn't) arbitrarily throw away the location (timezone info). This really leaves me with 1) and 2) above as my options.

Here is the question for the time experts here:
    * Is there a denser way to store time zone info?
I have looked at the IANA site and Howard's code for a unique integer identifier, etc. and I think the answer is no. However, I want to check before moving ahead.

**Comment by HowardHinnant** [comment]
One could store local time plus the UTC offset:
```
13:05:06 +0300
```
And this allows you to know both the local time and the UTC time (UTC is 10:05:06 in this example).  However the offset does _not_ allow you to recover the time zone.  So although you might know the local time as expressed, you could not know the local time + 5min as expressed because there might be a discontinuity in the local time during the next 5min.  If that is an acceptable cost, the offset takes up only 5 more char, and is thus shorter than the time zone name.

If you don't want to loose _any_ information, the only real choice is to store the local time along with time zone name.  You don't need to store the abbreviation because given the local time and time zone name, you can recover the abbreviation from the IANA database:
```
    date::local_time<std::chrono::seconds> t3l;
    std::string t3_time_zone_name;
    ss >> date::parse("%F %T %Z", t3l, t3_time_zone_name);
    auto t3 = date::make_zoned(t3_time_zone_name, t3l);
```
`t3` is now a `zoned_time` with all the information about that `{local_time, time_zone}` pair that there is to know, including the abbreviation and UTC equivalent (and more).  And you can do arithmetic on the `local_time` (or equivalent `sys_time`) with confidence that the arithmetic will respect the local `time_zone` rules.

If you are storing a limited number of time zone names, you might be able to create unique abbreviations for those time zone names, and then map your abbreviations to your time_zone names prior to forming the `zoned_time`.  That might save you a few bytes per entry.

**Comment by neuraleskimo** [comment]
As usual, thank you very much!

Your last option was sort what I was hoping for, but as a part of a standard. I am surprised that time zones are not assigned a globally unique integer in addition to a string. I am particularly surprised because storing times with time zones to relatively expensive on storage. Well, I should say relative to storing short integers or reals.

I doubt anyone is interested, but after thinking about it a little more, I really like adding metadata to each file denoting timezone (option 2 in my original post) as I import, clean, and validate it. Every other approach ends up repeating the same information in an given file. Because I have between 10^9 and 10^10 rows total, each additional byte cost 1GB in total storage (assuming 10^9 rows). Adding five bytes, for example, makes that 5GB. At 10^10 rows, that becomes 50GB. With the data growing non-linearly, I decided not to spend the bytes.

I thought briefly about storing the clean and validated data as binary files, but as I hinted at above, it is really a wash because most of the data is small integers (e.g., 5) or reals (e.g., 1.2345). The only gain is converting a 47-byte string into a 8-byte long. That sounds like a big win, but it is offset by the short integers and reals.

**Comment by HowardHinnant** [comment]
The problem with assigning numeric identifiers to timezones within the standard is that the full list of timezone names changes over time.  Very rarely is a time zone eliminated (I've seen it happen once).  But new time zones come into being.  We could just give them the highest number plus 1, but then one couldn't count on properties such as the numerical order being the same as the alphabetical order.

And I guess the real reason is that this library simply reflects the IANA database (https://www.iana.org/time-zones), without adding to it or subtracting from it.  This makes the database maintenance their problem instead of mine. :-)

**Comment by neuraleskimo** [comment]
I wouldn't suggest that you take that on. One of the reasons I didn't roll my own numeric id (as you excellently suggested) is that I am well aware that the only bug-free code is the code that *I* don't write. That's why I rely on code from the experts like you, Stepanov, and Stroustrup. ;-)

**Comment by HowardHinnant** [comment]
How many time zones do you have to deal with?  I hope not all of them...

**Comment by neuraleskimo** [comment]
Oh, that is a good question... No, not all of them. Really the major ones around the world. New York, London, Tokyo, etc. The major technology, economic, and political centers. One to two dozen-ish.
