### ISSUE TITLE
About a nammed getter to get the representation on classes like year/month/day/weekday

### ISSUE THREAD

**Issue by viboes** [HowardHinnant/date#226]
Wondering if we need here a named member function `value()`/`count()`/`underlying()`so that clients don't need to `static_cast<unsigned>(x)` to the representation type.

For example in https://github.com/HowardHinnant/date/blob/fa6529a2fccc4076e30b0e5ae0b5aaf7ff57ab49/include/date/date.h#L1399

```
CONSTCD11 inline bool
operator<(const month& x, const month& y) NOEXCEPT
{
    return static_cast<unsigned>(x) < static_cast<unsigned>(y);
}
```

could be 

```
CONSTCD11 inline bool
operator<(const month& x, const month& y) NOEXCEPT
{
    return x.underlying() < y.underlying();
}
```

What is the advantage to casting to unsigned when the representation is unsigned char?

**Comment by HowardHinnant** [comment]
Once compilers are all up to date (and the current ones are), the syntax for this will be _uniform-initialization syntax_:
```c++
constexpr inline bool
operator<(const month& x, const month& y) noexcept
{
    return unsigned{x} < unsigned{y};
}
```
Unfortunately there's a bug in gcc-pre-6.something that doesn't swallow this syntax and so the implementation (but not the documentation) uses the clumsier `static_cast` syntax just as an aid to portability with older compilers.

It is hoped that the need for casting from `month` (et al) to integrals will be minimized as time goes on as this breaks the type safety system just as using `.count()` on `duration`s does.

The advantage of the uniform-initialization syntax is well, uniformity.  This uniformity helps reduce the apparent API of the library as a whole.  If you need to explicitly convert one type to another (and this _is_ an explicit conversion), the syntax is `U{t}`.

The rationale for having the conversion to `unsigned` instead of to `unsigned char` is that `unsigned char` is too unfriendly to work with.  For example:
```c++
cout << {unsigned char}m << '\n';
```
is both clumsier syntax, and it doesn't stream out a decimal number.  But this does exactly what you want:
```c++
cout << unsigned{m} << '\n';
```
Though there is a `format` function so that this cast isn't needed either:
```c++
cout << format("%m", m) << '\n';
```

**Comment by viboes** [comment]
Agreed `unsigned{x}` is better than `static_cast<unsigned>(x)`.

I'm all for explicit conversions and using `target_type{y}`is the good syntax. However, I believe sometimes we don't want exactly to convert to a specific type, but just to the underlying representation, without having to know the type. `duration::count()` do this well, but  `duration::rep` is rarely `char` and so doesn't has the stream issue.  

For the stream insertion issue, I've a promote function that takes care of printing chars

https://wandbox.org/permlink/KqFAGEjz68LjqB07

The use in your case is surely more verbose than

```
cout << promote_to_printable(m.underlying()) << '\n';
```

but the intent is clear.

Adding an overload for month could allow something shorter that convey the intent.

```
cout << promote_to_printable(m) << '\n';
```

I recognize that this is maybe less friendly, but I don't want to have to use `unsigned(x)` for some types and `int{x}` for other just because `signed char`/`unsigned char`/`char` doesn't print well.

Of course, something shorter than `promote_to_printable` will be better.

**Comment by HowardHinnant** [comment]
If I add `promote_to_printable(m)`, I have no doubt that people will ask:  Why do I need to do that?
```c++
cout << m << '\n';
```
is working just fine for me.  And so is:
```c++
cout << format("%m", m) << '\n';
```
I don't really need or want to dress up this cast to much, because it is rarely a good idea to make that cast.  And I _really_ don't want to imply that `month` has to be promoted to be printed.

**Comment by viboes** [comment]
I understand and I'm not asking you to add it. Just wanted to have your feedback on how I could manage with this situation. I have a lot of strong types that give access to the underlying type. and I have of course this annoying print issue.

BTW, this doesn't works well

```
cout << m << '\n';
```

as month doesn't prints. The user needs 

```
cout << unsiged{m} << '\n';
```

I don't have the unsigned conversion and so this doesn't work neither for me and I don't have a formatter. 

I'll need yet more feedback if you don't mind.

Would you agree that using unsigned{x} all around the code is weird? Why do we need to cast to unsigned in order to be able to compare it, implement arithmetic, ...? What is wrong with a named accessor?
IIUC the "reason d'etre" of providing the unsigned conversion was to be able to print it.  
Aside needing a lot of changes in the code, what would be wrong replacing the unsigned conversion for a named accessor that returns unsigned so that the user doesn't depend on the type and the result is printable?

**Comment by HowardHinnant** [comment]
I think there's a disconnect somewhere.  Here's working code:

https://wandbox.org/permlink/EmYXj7W4Sv9xFmw3

It is printing and comparing months, and there's no `unsigned{x}` in sight.  Yes, the implementation needs to do a lot of `unsigned{x}`, but the clients of date.h don't.  I'm not understanding why you're needing this cast "all around the code".  Or is your position that the _implementation_ should have better syntax?

**Comment by viboes** [comment]
You are using `date` in the example.  I'm not talking about the `date` io.
 
What if I'm using  just `month`, `weak`, `day` and I need to define operations that work with these types?

Having a way to get the underlying value would allow the implementation of to avoid the explicit `unsigned{m}`. I find `underlying(m)` or `m.underlying()` more generic, stable and it coveys better the intent. When you need to print it, maybe  `unsigned{m}` is a better choice.

BTW, the same issue appears for C++ enum class.

Anyway, be free to close the issue, if you don't find the `underlying` function. 

P.S. I'm asking because I'm working on a *Wrapping* concept that generalize Enums and other wrappers as your strong types `month`, `weak`, `day`. A *Wrapping* allow to get the underlying type and the underlying value in a generic way.
