### ISSUE TITLE
Bug using make_zoned and adding durations ?

### ISSUE THREAD

**Issue by jkhoogland** [HowardHinnant/date#231]
Hi Howard,
I am seeing some unexpected output, which does not make sense.
This is on OSX 10.12.6, clang 9.0.0, c++11. 
Library is as of current HEAD (e12f7c66f0b8c554298dc0c82c3d41e2c4b4c53b).

Any idea what I am missing ?
Thanks,
Jiri

It looks like there is something going wrong:

```
TEST( DateTime, Add_Bug )
{
    using namespace date;
    using namespace std::chrono;

    auto const tpUTC = sys_days{ 2016_y / jul / 8 } + hours( 13 ) + minutes( 14 ) + seconds( 15 );
    auto const tz    = std::string{ "America/New_York" };
    auto const zt    = make_zoned( tz, tpUTC );

    int numMonths  = 3; // shift local time by 3 months
    auto const tp  = zt.get_local_time() + months{ numMonths };
    auto const zt2 = make_zoned( tz, tp );

    std::cout << "zt  = " << zt << std::endl;
    std::cout << "zt2 = " << zt2 << std::endl;

    // output on OSX 10.12.6, clang 9.0.0, c++11:
    //
    //    zt  = 2016-07-08 09:14:15 EDT
    //    zt2 = 2016-10-07 16:41:33 EDT
    //
    // expecting:
    //    zt2 = 2016-10-08 09:14:15 EDT !!!

    auto const ltp = local_days{ 2016_y / oct / 8 } + hours( 13 ) + minutes( 14 ) + seconds( 15 );
    EXPECT_EQ( make_zoned( tz, ltp ), zt2 );
}
```

**Comment by HowardHinnant** [comment]
Hi Jiri,

This lib lets you do two "kinds" of computations:

*  Chronological computations.

* Calendrical computations.

It is a subtle distinction, but your example is perfect to demonstrate the difference.

A _chronological computation_ is one which adds/subtracts uniform units of time duration to/from some point in time.  It models the passage of physical time, and can be very useful when computations concern physical processes such as astronomy, biology and weather.  One can even do chronological computations with the units of months and years, and in this case the uniform units represent the average length of the civil months and years.

A _calendrical computation_ respects the irregularities of calendar and time keeping systems.  Some months are longer than others.  Some years are longer than others.  Even some days are shorter/longer than others.  Calendrical computations are best used when scheduling events for people.

Your example is performing a chronological computation, but intending to perform a calendrical computation.  Here is how you can make it do the latter.

Replace:
```c++
auto const tp  = zt.get_local_time() + months{ numMonths };
```
with:
```c++
auto tp  = zt.get_local_time();
auto tp_days = floor<days>(tp);
auto local_tod = tp - tp_days;
tp_days = local_days{year_month_day{tp_days} + months{ numMonths }};
tp = tp_days + local_tod;
```
Explanation:

`tp` is a chronological entity.  Under the hood it is nothing more than a count of seconds since the epoch.  And you can add/subtract any `chrono::duration` to/from it, and get another `time_point` measured since the epoch.  And `months` is just another `chrono::duration` whose period is equal to the average civil month.

To perform the calendrical computation, one must first convert to a calendrical type, then do the computation, then convert back to the chronological type.  The first step is to convert the `{count-of-seconds}` data structure to a `{count-of-days}` data structure.  This is what `floor<days>` does.

Now you have two data structures:  `{count-of-seconds}` and `{count-of-days}`, and their difference is simply the `chrono::duration` measuring the local time since midnight (in `seconds` since `seconds` is the `common_type` of these two units).

Now you can convert `tp_days` to the _calendrical_ type `year_month_day`, perform the calendrical computation, and then convert back to a `{count-of-days}` data structure (which is called `local_days`) and assign that for the new value of `tp_days`.

Finally just add your local time-of-day back to your `{count-of-days}` to create your new `{count-of-seconds}` value and you're done!

[Here is a stack overflow answer](https://stackoverflow.com/a/43018120/576911) which goes over the same subject matter, but also includes the effect of doing the computation in UTC (as opposed to a specific time zone).

Hope this helps.

**Comment by jkhoogland** [comment]
Right, thanks for the detailed explanation,
I should have more thoroughly checked the documentation.
Much appreciated,
Jiri
