### ISSUE TITLE
runtime_error on Mac OS High Sierra

### ISSUE THREAD

**Issue by itachiluan** [HowardHinnant/date#246]
Hi, I have just updated my OS to High Sierra and the tz library seems to give me this error:
`terminating with uncaught exception of type std::runtime_error: default/Europe/Dublin not found in timezone database`
I checked the tz.cpp file and it seems that the `current_zone()` function returned the result as something like `/usr/share/zoneinfo.default/Europe/Dublin` and then truncated to `default/Europe/Dublin`
This only happens after I updated to High Sierra, and I have just did a work around currently for myself which just removed the "default/" bit from the result, seems to be working for me at the moment. Just wondering if it was an actual error caused by the High Sierra updates or something wrong with my system config. Thanks!

**Comment by HowardHinnant** [comment]
I believe this is fixed with this commit:
https://github.com/HowardHinnant/date/commit/22a229af9106c032949f9a87a9a4fd9cc667a1ee

Apple saw fit to fiddle with where they placed the zic-compiled IANA database on the disk.  This commit is intended to be compatible with both High Sierra, and pre-High Sierra.

Please let me know if the above commit (or any commit afterwards up to tip-of-master) does not fix this issue.

**Comment by itachiluan** [comment]
Hi Howard,
Thanks for the very quick response.
I must have been trying the High_Sierra branch and it didn't seem to work...I should have just tried the master branch.

The latest master branch is working, thanks!
Apologies for any inconvenience caused:)

**Comment by HowardHinnant** [comment]
Never an inconvenience!  It is good to know that the lib is being used. :-)
