### ISSUE TITLE
parse cant parse %Y | %Y-%d

### ISSUE THREAD

**Issue by baslr** [HowardHinnant/date#253]
Try to parse just a year.
```C++
    system_clock::time_point tp;    
    std::istringstream in{"2017"};
    in >> parse("%Y", tp);
    std::cout << tp << std::endl;
    // 1970-01-01 00:00:00.000000000
```
Try to parse year and month.
```C++
    system_clock::time_point tp;    
    std::istringstream in{"2017-12"};
    in >> parse("%Y-%d", tp);
    std::cout << tp << std::endl;
    // 1970-01-01 00:00:00.000000000
```
Parses year, month and day.
```C++
    system_clock::time_point tp;    
    std::istringstream in{"2017-12-12"};
    in >> parse("%Y-%d-%m", tp);
    std::cout << tp << std::endl;
    // 2017-12-12 00:00:00.000000000
```
JavaScript can parse a year.
```js
new Date("2017")
Sun Jan 01 2017 01:00:00 GMT+0100 (CET)
```

**Comment by HowardHinnant** [comment]
There is both an explanation for this behavior, and a way to do what you want.

First the explanation:

`system_clock::time_point tp` is an integral count of time units (typically microseconds or nanoseconds) since 1970-01-01 00:00:00 UTC.  When you try to `parse` into `tp`, if the library can't unambiguously form the count that lives inside of `tp`, it will set `failbit` in the stream `in` and not modify `tp`.

Only your 3rd program succeeds, as parsing "2017-12-12" will assume "00:00:00 UTC".  But parsing just year, or just year and month without the day, will not assume a default month or default day.

To parse just a year:
```c++
    date::year y;    
    std::istringstream in{"2017"};
    in >> parse("%Y", y);
    std::cout << y << '\n';
    // 2017
```
To parse a year and month:
```c++
    date::year_month ym;    
    std::istringstream in{"2017-12"};
    in >> parse("%Y-%m", ym);
    std::cout << ym << '\n';
    // 2017/Dec
```
You can parse a year, month,day into either a `system_clock::time_point`, or a `sys_days` (which is just a `system_clock::time_point` with a precision of `days` instead of `microseconds`), or a `date::year_month_day`, which is literally a `struct {year, month, day}` with getters for each field.

**Comment by baslr** [comment]
Hi Howard,

thank you for your explanation. `year` and `year_month` was exactly what I missed.

Is
```C++
    year y;
    std::istringstream in;
    in = std::istringstream{"123456"};
    in >> parse("%6Y", y);
    std::cout << y << std::endl;
    std::cout << in.fail() << std::endl;
    // -7616
    // 0
```
a overflow problem?

**Comment by HowardHinnant** [comment]
Yes, that's exactly what it is, and I should check for a legal range on parse!

Fixed: https://github.com/HowardHinnant/date/commit/1902b8e8fb03a7c41316fa80c589a51aa3923aa9

Thanks!

**Comment by baslr** [comment]
One last question:

```C++
in = std::istringstream{"2017-10-10"};
in >> parse("%Y", y);
std::cout << y << std::endl;
std::cout << sys_days(y/1/1) << std::endl;
std::cout << in.fail() << std::endl;
```
its working but I expected it to fail.

**Comment by HowardHinnant** [comment]
Try appending these lines after showing the stream has not failed:
```c++
    std::string leftover;
    getline(in, leftover);
    std::cout << leftover << '\n';
```
:-)

**Comment by HowardHinnant** [comment]
Btw, I didn't get the range check on year correct the first time.  Needs one more commit:  https://github.com/HowardHinnant/date/commit/443a29df531a5e093409e3974f84362a12b03cac

**Comment by baslr** [comment]
Thanks again.
I watched your great cppcon talks about chrono, date.h and tz.h 👍
