### ISSUE TITLE
how to parse "2017-02-33"

### ISSUE THREAD

**Issue by baslr** [HowardHinnant/date#294]
Hi,

is it possible to parse "2017-02-33"?
I tried unsuccessfully.
```
year_month_day ymd = year{2000}/1/1;
auto in = std::istringstream{"2017-02-33"};
in >> parse("%Y-%m-%d", ymd);
bool failed = in.fail();
std::cout << failed << std::endl;
std::cout << ymd << std::endl;
```
results in
```
1
2000-01-01
```
It is possible to parse a single day (33) with %d.

**Comment by HowardHinnant** [comment]
Not with `%d`, it will range check.  To avoid the range check you could parse integers, and then feed the integers into a `year_month_day`:  `auto ymd = year{y}/m/d;`.  This will set the fields to 2017, 2, and 33, respectively.

**Comment by tomaszkam** [comment]
If year_month_day is a field type that already allows invalid values, wouldn't it be fine to parse any set of values, and let the user check the result using ymd.ok()? You can still parse the values for local_days, if you want the correct date.

**Comment by HowardHinnant** [comment]
There's no way to make everyone happy on this issue.  Other's clients will demand that they need `parse` to detect & fail with invalid dates.

**Comment by tomaszkam** [comment]
To be clear not proposing a change, because would be breaking.

If we allow invalid year_month_days, people wanting to fail would be still able to do so, by checking !ok() after parse, so it would make both requirements supported. Maybe important in cases when you want to parse string with locale-dependent name of months.
However, the meaning of %d for parse would become context dependent.

**Comment by HowardHinnant** [comment]
Closing. The design phase of this library is now locked down and tracking the draft C++20 spec: http://eel.is/c++draft/#time
