### ISSUE TITLE
abbrev holds the offset hours to UTC instead of the actual abbreviaton of the time zone

### ISSUE THREAD

**Issue by aacirino** [HowardHinnant/date#306]
I am on macos 10.11.6, using clang 6.0 and the latest version of the date library. I can't figure out why the abbrev data keeps the hours offset of my time zone (-03 for America/Sao_Paulo) instead of the actual characters for this time zone. This the output of `std::cout << "sysinfo : " << t.get_info() << '\n';`:

sysinfo : 2018-02-18 02:00:00
2018-11-04 03:00:00
-03:00:00
00:00
-03

and this is the output of `std::cout << format("%a, %b %d, %Y at %I:%M %p %Z", t) << '\n';`:

Sun, Mar 11, 2018 at 07:11 PM -03

**Comment by HowardHinnant** [comment]
This is due to changes in the IANA tz database made last December which changed the abbreviation for this time zone from alphabetic to numerical.  Here is the commit that did this:

https://github.com/eggert/tz/commit/c9e6ef07cc6f1062ddd032c96c5172f403c0058f#diff-109e03a0a154807a82e70bef80657ebbL1043

Changing this behavior is not something under my control.  However, if you believe this change to be in error, and can point to publicly available (preferably official) documentation stating that BRT/BRST are the widely accepted abbreviations (by the local population), then you can get this behavior changed by mailing this list: https://mm.icann.org/mailman/listinfo/tz  After such a change is made to the IANA tz database by this unofficial group of volunteers, my library will pick up that change.

**Comment by aacirino** [comment]
Hi Howard, I appreciate your feedback. I wasn't aware of this change and it doesn't make sense to me. I will try to convince the people that maintains the database.

**Comment by HowardHinnant** [comment]
Excellent.  I will follow your progress with interest.  These changes have been somewhat controversial on this list.
