### ISSUE TITLE
Wrong date by one

### ISSUE THREAD

**Issue by gamagan** [HowardHinnant/date#325]
I'm not sure what's going on. I want to believe it's something that I'm doing, but the library is giving me the wrong date. This is my first time using it, so...

At the moment of this writing, it is 10:36pm, EST on April 4, 2018

The clock on my PC is correct. I'm using Windows 10, 64bits. Compiler is Visual Studio 2017, latest updates.

The following code gives me the date 2018-04-05, which is one day off. The code is at the very beginning of a WinMain() entry point in a C++ application.

```
	using namespace date;
	auto startTime = std::chrono::system_clock::now();
	auto today = trunc<days>(startTime); // tried floor, trunc, round

	std::stringstream ss;
	ss << today;
	std::cout << "date: " << ss.str() << "\n"; 
```

**Comment by HowardHinnant** [comment]
Hi @gamagan! There's not an error in your code, just in your interpretation of it.  Perfectly understandable.  Humans have made time so complicated, we can't possibly understand it! ;-)

An invariant you can count on is that `system_clock` represents UTC, not local time.  This library can give you local time, but that's more work.  `zoned_time` is the typical way to get local time.

Specifically, in your program, `startTime` is a measure of duration since 1970-01-01 00:00:00 UTC.  And `today` is a count of days since 1970-01-01 00:00:00 UTC.  When you print it out, that count of days gets converted to a human readable calendar date, but still in terms of UTC.  Indeed, the time you printed out was at 2:36am, UTC on April 5, 2018.

To get local time, first make sure you've followed the [installation directions](https://howardhinnant.github.io/date/tz.html#Installation), and then do:

```c++
#include "date/tz.h"
#include <iostream>

int
main()
{
    using namespace date;
    std::cout << "date: " << format("%F\n", make_zoned(current_zone(),
                                                       std::chrono::system_clock::now()));
}
```
The `make_zoned` factory function creates a type of `zoned_time<system_clock::duration>` which creates a local time with your computer's current local time zone.  And the `format` function with `%F` just takes the local date out of that `zoned_time` and prints it in `yyyy-mm-dd` format.

I'm in the same timezone as you and this just printed out for me:
```
date: 2018-04-04
```

**Comment by gamagan** [comment]
Oh, thank gad. I kept telling myself that there must be a logical explanation; there's no way HH's code is buggy. I'm glad this was the case.

Thanks for the quick response and the detailed explanation. This probably means that I didn't read enough of the manual.
