### ISSUE TITLE
from_stream(stream&, fmt, duration&) rejects units longer than hours

### ISSUE THREAD

**Issue by evsh** [HowardHinnant/date#329]
Specifically, [this line](https://github.com/HowardHinnant/date/blob/master/include/date/date.h#L7391) assumes that durations may not be measured in days, months, or years.

**Comment by HowardHinnant** [comment]
This is by design.  `from_stream` is tailored to the [parsing flags](https://howardhinnant.github.io/date/date.html#from_stream_formatting) which include %H, %M and %S for durations.  `from_stream` is not set up to handle more general units of durations such as weeks, fortnights, and centuries.

I have in the past coded a generalized stream extraction operator for durations that basically reversed the effects of the stream insertion operator.  That remains a possibility for the future.  But for now, `from_stream` is really just `strptime` with better manners.

**Comment by evsh** [comment]
Sorry, I can't understand your reasoning. `from_stream(stream&, same_format_string, time_point&)` parses  years just fine. What's the difference?

**Comment by HowardHinnant** [comment]
It doesn't parse the _duration_ `years`.  It parses the partial calendar type `year` which can be controlled by the flags %Y, %y, %C, %G, or %g.  There is no flag to parse a duration equal to the length of the average civil year (365.2425 days).

I admit to being a _little_ inventive with the [POSIX strptime flags](http://pubs.opengroup.org/onlinepubs/009695399/functions/strptime.html), but I tried to keep that to a minimum.  The rationale for that strategy is that I wanted the format/parse flags to already be familiar to my customers, as opposed to them having to learn a completely new "mini language" for parsing.

**Comment by evsh** [comment]
To clarify my question: duration becomes a time point only when time system is specified, e.g. '2008-04-12T07:39:15.57' is still a duration, and '2008-04-12T07:39:15.57 TDB' is a time point. If a string does not contain time system name, the library can't know is it a duration or a time point.

My use case: I read a time stamp from an image file, and it is defined in spacecraft clock system. The system was synchronised with the UTC at a point in the past, but now those time stamps are just offsets in its drifting time system. I want to reflect that in my program and return duration objects, but I can't read them directly and have to read `time_point` instead.

**Comment by HowardHinnant** [comment]
Thanks for the clarification of the problem you are facing.  It sounds most interesting.

May I suggest that you parse into a `local_time<Duration>` instead of a `duration`?

`local_time` is a `time_point`, but with as yet unspecified clock.  It is much like the `void*` of pointers.  This gives you a type system to keep these timestamps distinct from both durations and UTC (`sys_time`/`utc_time`).  If at some point you discover the correct offset (say during a syncing process), you can convert the `local_time` to a `sys_time` by extracting the `.time_since_epoch()` and applying the offset correction.

The parse flags will all work with `local_time` of whatever precision you require.

**Comment by evsh** [comment]
Do I understand you correctly that for duration you want to use only stable units, because `from_stream()` can not inform or obtain a hint what to do with leap seconds and days?

**Comment by HowardHinnant** [comment]
Actually there is a `from_stream` overload that takes `utc_time`.  `utc_time` is just like `sys_time`, but takes leap seconds into account.

The rationale for the current design is that `from_stream` evolves from the POSIX C function `strptime`, which most of my clients are migrating from.  `strptime` has a relatively well specified set of parsing flags.  And I have tried to deviate from these established flags as little as possible.  When I do deviate, that deviation is in ways that most people will see as minor corrections to the POSIX spec, as opposed to a redesign.

**Comment by evsh** [comment]
> May I suggest that you parse into a local_time<Duration> instead of a duration?

Thank you, `local_time` suits my purposes better. Yet I can't understand how to handle leap seconds/days in that case. The spacecraft clock follows UTC rules and when reading from a string I was assuming that converting the string to duration, those leap seconds will be counted in the same way as it is done for the UTC system. But unspecified clock can't have leap seconds, right?

**Comment by HowardHinnant** [comment]
That is true.  The parse into `local_time` will fail if you try to parse 60 in the seconds field.  You'll need to parse into `utc_time` to handle that.

To keep your type safety, perhaps it would be best to immediately turn your `utc_time` into some other time_point, perhaps `local_time`, or perhaps `chrono::time_point<spacecraft_clock, some_duration>`.  In the latter case, you could write your own `from_stream` overload that calls the `utc_time` `from_stream` overload in order to implement the parsing.

I don't know enough about your problem to know if the `spacecraft_clock` idea is a good one or not.

**Comment by evsh** [comment]
Thank you! A `spacecraft_clock` class plus i/o overloads seems to the most logical solution.
