### ISSUE TITLE
Issue with MSVC and /Zc:__cplusplus

### ISSUE THREAD

**Issue by AndrewPardoe** [HowardHinnant/date#331]
The `#if` side of the definition of `string_literal` on line 7522 fails with a correctly set `__cplusplus` in MSVC 15.7 preview 3 and above. The `#else` side on 7908 appears to work. 

We know about the bug (#600264) and will fix it.

**Comment by HowardHinnant** [comment]
Thanks for letting us know!  If you decide you need me to shuffle MSVC back to the `#else` side, just let me know.  But I'm glad this little project is helping make MSVC better and better.

**Comment by AndrewPardoe** [comment]
Hopefully we can fix this quickly. If not, we might ask for a one-off.

**Comment by xiangfan-ms** [comment]
BTW, the two source workarounds:
1. changing 'std::enable_if_t<1 < sizeof(U)>' to 'std::enable_if_t<(1 < sizeof(U))>'
 While the parentheses aren't required, it does clarity the source code and improves the readability.
2. changing 'std::is_same<>{}' to 'std::is_same_v<>')
 I think the workaround is actually better than the current implementation :-). It is semantically the same and is cheaper to compile.

**Comment by HowardHinnant** [comment]
I haven't reviewed these changes in detail yet.  But I definitely want VS-latest to work with this lib in as high a quality as practical.  So I'm highly motivated.  Things I'll be looking for are C++11 compatibility.  But I suspect we're talking about a C++14 and higher branch anyway.  And I have a previous history of making minor syntactical changes to accommodate other compilers.

This is my night job and I took last night off. :-)  If you put up a P/R, I'll definitely review it, and if I don't accept it, I'll recommend changes you can make to get it accepted.

Stylistically, I prefer  `std::is_same<>{}` to `std::is_same_v<>`.  I wasn't crazy about the `_v` additions for that reason, though I did not object to them either.  They introduced an alternative name for something that already had a good name with the same number of characters.  Its only advantage was to benefit platforms that were behind in `constexpr` compliance.  But style is a secondary concern to getting all platforms up and running.  I mention it just because you asked.

**Comment by HowardHinnant** [comment]
Oh, just noticed that `is_same_v` is C++17.  No can do.  I can do `is_same<>::value` instead.  Objectively uglier style, but up-and-running takes precedence.

**Comment by HowardHinnant** [comment]
Not resolved yet.  I need someone besides me to take point on VS.  I can advise, but I can't test.

**Comment by zlojvavan** [comment]
if no one is using date lib with vs and /Zc:__cplusplus then feel free to advise me how to fix aforementioned specific problem so we could advance further

**Comment by HowardHinnant** [comment]
What version of VS do you use?  And what is the `_MSC_VER`?

**Comment by zlojvavan** [comment]
Microsoft Visual Studio Community 2017 
Version 15.8.9
VisualStudio.15.Release/15.8.9+28010.2050

_MSC_VER 1915

**Comment by HowardHinnant** [comment]
Ok, I note that `enable_if` for `make_zoned` are ifdef'd out for `_MSC_VER > 1900`.  What happens if you put those back?

**Comment by zlojvavan** [comment]
I was able to build the project when made string_view taking constructor unconditional with the following:
#if HAS_STRING_VIEW
    template <class T = TimeZonePtr,
              class = typename std::enable_if
              <
                  /*std::is_constructible
                  <
                      zoned_time,
                      decltype(zoned_traits<T>::locate_zone(std::string_view()))
                  >::value*/true
              >::type>
        explicit zoned_time(std::string_view name);
#else

**Comment by HowardHinnant** [comment]
Ok, thanks!  I'll act on this this weekend.

**Comment by HowardHinnant** [comment]
Ok, try this out: https://github.com/HowardHinnant/date/commit/23b1f007fe2f0eae33333286785560693d5f6eb3

**Comment by HowardHinnant** [comment]
Make that: https://github.com/HowardHinnant/date/commit/5f34c4052377b390976dc93efaa143c678b7ee59

**Comment by DanielaE** [comment]
A proper fix is in `master` now.
