### ISSUE TITLE
weekday can't explicit conversion to unsigned

### ISSUE THREAD

**Issue by pmalakul** [HowardHinnant/date#344]
weekday can't explicit conversion to unsigned in your latest release.

**Comment by HowardHinnant** [comment]
Sorry about the API breakage.  It was forced by a significant number of clients objecting to the [0, 6] encoding as opposed to the ISO [1, 7] encoding.  So now the encoding is hidden, and you have to specify which encoding you expect when convert back.

The git commit log has notes on this, and the next release will have an API-breaking version number change and contain the same release notes.  For convenience here they are:

>     [API BREAKING] Remove conversion from weekday to unsigned
>     
>     * There has been a great deal of anguish over the encoding of
>       weekdays:  whether [0, 6] maps to [Sunday, Saturday] or
>       [1, 7] maps to [Monday, Sunday].  This commit attempts
>       to address that issue, but will break a small amount of
>       code at compile-time.  See below on how to fix that.
>     
>     * The weekday constructor used to accept [0, 6] to represent
>       [Sunday, Saturday].  It now accepts [0, 7] to represent
>       [Sunday, Saturday] with both 0 and 7 mapping to Sunday.
>     
>     * The conversion from weekday to unsigned has been removed.
>     
>     * To convert a weekday to unsigned replace:
>     
>           auto u = unsigned{wd};
>     
>       with:
>     
>           auto u = (wd - Sunday).count();
>     
>       This maps [Sunday, Saturday] to [0, 6], which is the
>       C/POSIX mapping.  If you prefer the ISO mapping
>       ([Monday, Sunday] -> [1, 7]), then do:
>     
>           auto u = (wd - Monday).count() + 1;

The VS-2013 error is a separate issue.  I'm not sure but `weekday(sys_days(ymd))` may fix it.

I'm leaving this open because I'm sure others are going to hit this same issue, and I want people to be able to easily find this issue.

**Comment by YimingYAN** [comment]
@HowardHinnant 

> The VS-2013 error is a separate issue. I'm not sure but weekday(sys_days(ymd)) may fix it.


Yes, it fixed it. Thanks.

**Comment by HowardHinnant** [comment]
Was it just one place that needed fixing?  Or would you like to submit a P/R to fix this (for credit in the git commit log)?

**Comment by pmalakul** [comment]
Just this one so far. Thanks it is now fixed.

**Comment by HowardHinnant** [comment]
Pushed the VS-2013 fixes: https://github.com/HowardHinnant/date/commit/d50970b32ae34defa849cc01856fa5ee28cd60a7
