### ISSUE TITLE
What should `%c` do when formatting `std::chrono::seconds`?

### ISSUE THREAD

**Issue by vitaut** [HowardHinnant/date#408]
The following example:
```c++
std::cout << date::format("%c", std::chrono::seconds(12345)) << "\n";
```
throws
```
libc++abi.dylib: terminating with uncaught exception of type std::__1::ios_base::failure: ios_base::clear: unspecified iostream_category error
```
when compiled and run on macOS with clang.

Is it the expected behavior?

**Comment by HowardHinnant** [comment]
Yes.  The `format` operation constructs an `ostringstream`, and sets the `failbit` in the exceptions mask.  This causes an exception to be thrown if there is a failure in the output operation.

`"%c"` formats the locale's date and time representation.  Since insufficient information was given to `format` to form a date, the `"%c"` operation sets `failbit`.

**Comment by vitaut** [comment]
Thanks for clarification, @HowardHinnant.
