### ISSUE TITLE
Does the parsing facility support sub-second time string (e.g. 12:30:10.010)?

### ISSUE THREAD

**Issue by lkpcampion** [HowardHinnant/date#412]
Hi,

The wiki/doc (https://howardhinnant.github.io/date/date.html#parse) suggests a dependency on time_get for localization/formats. time_get::do_get_time stores parsing result in std::tm, which only resolves down to an integer value of seconds ([0:60]).

What is the correct way to parse something like "01-Dec-2018 12:30:10.333" using this library?

Thanks~

**Comment by HowardHinnant** [comment]
You can do it like this:
```
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace date;
    using namespace std::chrono;
    std::istringstream in{"01-Dec-2018 12:30:10.333"};
    in.exceptions(std::ios::failbit);
    sys_time<milliseconds> tp;
    in >> parse("%d-%b-%Y %T", tp);
    std::cout << tp << '\n';
}
```

Yes, `time_get` is used, but only for the `%b` part of the format.  Everything else is locale-independent and `time_get` is not used for those parts.

Some implementations of `std::time_get` are buggy when asked to parse %a, %A, %b and %B (last time I checked, everything but libc++).  If you are caught by one of these bugs, and if you are happy with the behavior of the "C" locale, then you can completely bypass the need to use `std::time_get` by compiling with `-DONLY_C_LOCALE`.

**Comment by lkpcampion** [comment]
Thanks! This is great. I was worried I'd need to strip the subseconds part out first.

I do need to locale support though. Does it deal with internationalization too? -- like parsing 3月, and März as March if given the corresponding locale? There are also more than just month names in Asian languages, like '2018年' instead of just 2018, or 12月21日 instead of 12/21. Does parse() take the words as literals (like '-', '/') in the format (kinda like ICU)? Or it absorbs that as part of %b or %d (kinda like %0m, or %0d in get_time)?

**Comment by HowardHinnant** [comment]
Parsing `%b` (month name) is left to `time_get`, assuming you have not compiled with `-DONLY_C_LOCALE`.  If your `time_get` gets it right, then so does this lib.

`parse()` takes literals literally.  So if `月` is a literal in the format string, that will get parsed.  If it is part of the month name that the locale supports, then %b takes care of it.  However it is not absorbed into %b or %d by this library.  However, modified commands such as %Od _are_ locale dependent, and thus delegate the parsing to `time_get`.

In a nuthshell, if the %-command is locale dependent, it asks `time_get` to do the job, and otherwise this library does the job directly.

**Comment by lkpcampion** [comment]
Thank you. Let me give it a try. I am assessing between ICU and this for international/locale date parsing -- this is most helpful.

My original question is already answered. Thanks again for taking the time to response. Have a Merry Christmas!
