### ISSUE TITLE
check for `uncaught_exceptions` fails on Mac OS 10.11.6

### ISSUE THREAD

**Issue by mclow** [HowardHinnant/date#416]
https://github.com/HowardHinnant/date/blob/2cb4c340093b9f96622d8bc83c29154955e0d481/include/date/date.h#L1030

**Comment by mclow** [comment]
Sorry; hit return too soon.
The availability of `std::uncaught_exceptions` on Mac OS depends on the version of the OS *and* the language level, since it comes from the underlying ABI library.  On 10.11, for example, it does not exist, and this causes a compile-time failure on that OS

**Comment by beached** [comment]
Shouldn't the feature flag __cpp_lib_uncaught_exceptions be usable to detect this?  But even on(what I assume the newest Apple Clang) it isn't defined so maybe not

**Comment by beached** [comment]
Just noticed that Mojave with Apple LLVM version 10.0.0 (clang-1000.11.45.5) supports uncaught_exceptions but fails to set the feature flag.  😢

**Comment by beached** [comment]
It fixes the issue you are having, but I am not sure one can detect without a precompile compile test of something with uncaught exceptions otherwise.  Other compilers seem to play nice with other compilers (gcc trunk on Mohave and gcc/clang from ubuntu).

**Comment by mclow** [comment]
I repeat; it will not fix the issue I'm having, because Apple's not going to issue an update to "Apple clang 8.0.0". (or 10.11, for that matter).

**Comment by beached** [comment]
I'm sorry, I assumed that on that system the feature flag would not be set and would use uncaught_exception

**Comment by mclow** [comment]
Yes, but at the cost of breaking users on Mojave and High Sierra (at least).

**Comment by beached** [comment]
Am I misunderstanding the code? 
```cpp
#if defined( __cpp_lib_uncaught_exceptions )
                std::uncaught_exceptions() == 0 &&
#else
                !std::uncaught_exception() &&
#endif
```
My understanding is these "should" be synonymous in the outcome, both check if we are unwinding because of an exception(1 or more).

**Comment by HowardHinnant** [comment]
After giving this some thought, I'm closing this and the related PR as wontfix.  But I wanted to state my rationale:

Marshall brings up a good point about breaking binaries that are meant to run on older OS's which won't have `std::uncaught_exceptions()`.  Right now the developer can control this with `-std=c++14/17`.  If I make this change, that tuning knob is taken away from him.

I'm also not convinced that the current `__cplusplus >= 201703` test is correct.  It may be better to test on `__cplusplus > 201703` because C++20 is when `std::uncaught_exception()` is actually removed.  However, field experience has yet to provide any evidence that people need that change, so I don't want to move in that direction either at this time.
