### ISSUE TITLE
Compilation error with gcc 7.3.1 and clang 5.0.1

### ISSUE THREAD

**Issue by LukasWoodtli** [HowardHinnant/date#433]
I get the error:

`date/test/tz_test/zone.pass.cpp:14:5: error: static_assert failed ""
    static_assert( is_nothrow_move_assignable<time_zone>{}, "");
`
With with gcc 7.3.1 and clang 5.0.1 on Linux. 

It's related to the bugs:

https://github.com/HowardHinnant/date/issues/39#issue-131380016
and
https://github.com/HowardHinnant/date/issues/40#issue-131411708

But I'm compiling with new compiler versions.

Any hints why it's still not working?

Thanks!

**Comment by HowardHinnant** [comment]
My best guess is that your gcc is configured to use the old COW string as opposed to the C++11-conforming SSO string.  This is just a guess on my part, I don't know this for sure.

Here is a SO question on moving to the new ABI: https://stackoverflow.com/questions/34571583/understanding-gcc-5s-glibcxx-use-cxx11-abi-or-the-new-abi

This test failure is fairly benign.  What it means is that in your environment you won't be able to move assign a `time_zone`.  If you don't need to move assign a `time_zone`, no harm done.  If you do need to and try, it will be a compile-time error, not a run-time error.  So if your use cases with this library are compiling, then they are working.

**Comment by LukasWoodtli** [comment]
Thanks for the fast response!

I'll investigate on the string implementation. Probably I wont make excessive use of `time_zone` yet. So I won't see a lot of drawbacks when not beeing able to move assign a time_zone. And soon all this will become part of the stdlib anyway...

Thanks a lot for these cool libraries!

**Comment by HowardHinnant** [comment]
I just realized that I misread the error message, and gave you an incorrect analysis.  My eyes skipped right over the `nothrow` part of that `static_assert`.  You _will_ be able to move assign `time_zone`s.  It is just that in your environment, that expression won't be `noexcept`.  It still won't throw because gcc's COW string won't throw on move assignment.

But if you move assign a `time_zone` inside of a function marked `noexcept`, then there will be a minor code bloat as gcc will be forced to build an exception handling table that includes a call to `std::terminate`, even though that call to `terminate()` will never be exercised.  So there's a minor code size penalty.

**Comment by LukasWoodtli** [comment]
Thanks for your elaborate analysis.
I found that my GCC is configured with `--with-default-libstdcxx-abi=gcc4-compatible`.
This is on RHEL, which being an enterprise distro, has usually not the most current configurations set.
