### ISSUE TITLE
vs2017 can not use this library

### ISSUE THREAD

**Issue by Ultraman95** [HowardHinnant/date#437]
static CONSTCD11 year min() NOEXCEPT;
    static CONSTCD11 year max() NOEXCEPT;

can not complies

**Comment by HowardHinnant** [comment]
Windows defines macros for `min` and `max`.  `#define NOMINMAX` just prior to including Windows headers to inhibit this behavior.

**Comment by sharpe5** [comment]
I had the same problem.

I fixed it by including <date/date.h> in the precompiled header `pch.h` rather than in my `.cpp` file.

I found the easiest way to install this library is to use [vcpkg](https://github.com/microsoft/vcpkg):

```
vcpkg install date:x64-windows
```

To auto-add the include directory to all projects in Visual Studio:
```
vcpkg integrate install
```

I vote that this ticket be closed, as it definitely works.

**Comment by sharpe5** [comment]
Howard (and other contributors), thank you so much for developing this
library.

I spent 2 hours attempting to solve a problem with a range of standard
libraries, including Boost. Nothing was really working. Within 15 minutes
of trying your library, everything was working perfectly.

**Comment by HowardHinnant** [comment]
Thanks for the kind feedback!
