### ISSUE TITLE
Request of information/FAQ update comparison vs Boost Date Time

### ISSUE THREAD

**Issue by MicheleBe** [HowardHinnant/date#445]
Thanks Howard for the super lib and nice support you give with these library. I would be nice IMHO to add a section in the wiki/FAQ to explain a bit the comparison of this library against boost.Date_Time. 
I try to find out a justification and a fair comparison, but I didn't find it. I would like to adopt date but my department policy prefers always the adoption of boost library if the same functionality is available due to peer review process. 
Could you please support me writing a comparison or point me to an existing one?
Thanks in advance

**Comment by HowardHinnant** [comment]
How far does this go, and would you like to see it updated with anything more?

https://github.com/HowardHinnant/date/wiki/Boost-datetime-Examples-Translated

**Comment by MicheleBe** [comment]
Thanks for your kind answer. This is enough to demonstrated that funcionality wise they are equal but they ask me to clarify tow addiotnal points: 
Why another date library   and why is not  under the boost revision process especially since it is candidate as module for C++20...
Thaks again for your time and for your fantastic work.

**Comment by HowardHinnant** [comment]
> Why another date library?

I feel like this is the only date library that integrates well with `std::chrono`.  Indeed, there is code where it is difficult for newcomers to see where `date` ends and `chrono` begins because the transition is so seamless:

```
system_clock::time_point tp = sys_days{May/16/2019} + 15h + 51min + 17s;
```

It also has some features that `boost::datetime` doesn't have such as full history support of the IANA tz database, and ease in importing current changes to the IANA tz database.  I.e. "old time points" are correctly translated between local time and UTC.

> why is not under the boost revision process especially since it is candidate as module for C++20

Because I got the field experience I needed from this github site to polish and refine the design over the course of several years prior to submitting it for consideration to the C++ standards committee.  

This is not the first time that I have been involved with getting something standardized without going the boost route.  Indeed, `chrono` itself did not go through boost, though it was heavily influenced by `boost::datetime`.  `boost::chrono` came _after_ `std::chrono` was proposed, not before.

**Comment by MicheleBe** [comment]
Thanks for the explanation! I will maybe come back if I more details are required.
