### ISSUE TITLE
double year_month_day

### ISSUE THREAD

**Issue by p-groarke** [HowardHinnant/date#483]
Hello,

The `year_month_day` type (and others) seem to be hardcoded to `ints`. This sets a precedent for `std::chrono`, which works beautifully with floating point types. Is there a (humanly readable) way to use date when working in floating-point time?

For example :

```c++
using dseconds = std::chrono::duration<double>;
using dminutes = std::chrono::duration<double, std::ratio<60, 1>>;
using dhours = std::chrono::duration<double, std::ratio<3600, 1>>;

using ddays = std::chrono::duration<double,
		std::ratio_multiply<std::ratio<24>, dhours::period>>;

using dweeks = std::chrono::duration<double,
		std::ratio_multiply<std::ratio<7>, ddays::period>>;

using dyears = std::chrono::duration<double,
		std::ratio_multiply<std::ratio<146097, 400>, ddays::period>>;

using dmonths = std::chrono::duration<double,
		std::ratio_divide<dyears::period, std::ratio<12>>>;

using dsys_days = typename date::sys_time<ddays>;
using dsys_seconds = typename date::sys_time<dseconds>;

// ...

auto t = dsys_days(2020_y / date::jan / 1_d); // How would one achieve this? and vice versa
```

**Comment by HowardHinnant** [comment]
This is quite do-able.  I'm first going to presume that "floating-point time" is double-based count of days since 1970 (aka, `dsys_days`).  The easiest way to form that type is:

```
    using ddays = std::chrono::duration<double, date::days::period>;
    using dsys_days = typename date::sys_time<ddays>;
```

Now you can convert a calendrical expression to `dsys_days` with:

```
    using namespace date::literals;
    dsys_days t = date::sys_days{2020_y / date::January / 1_d};
```

And you can reverse that conversion by using `round` and whatever integral duration you desire to get it back to an integral-based count, for example:

```
    date::sys_seconds s = date::round<std::chrono::seconds>(t);
```
And then you can convert this integral-based `time_point` back to a calendrical type, for example:

```
    date::year_month_day ymd = date::floor<date::days>(s);
```

**Comment by p-groarke** [comment]
I knew you'd have thought of something for this, amazing work as always 👍 

Yes by floating point time I mean computations (which don't require very high precision) are all done with double. They are rounded when going to output (whatever that is). clock ints -> double computations -> ints. First time trying this out with dates however.

On another note, does it make sense to use the `high_resolution` clock with date? As far as I can tell, date is 100% `system_clock`.

**Comment by HowardHinnant** [comment]
`date` is 100% `system_clock`, and if you include "tz.h", some new clocks too:  `utc_clock`, `tai_clock` and `gps_clock`.

It doesn't make any sense to use `high_resolution_clock` with `date` because (in general), `high_resolution_clock` has no relationship with the civil calendar.  For example on my platform `high_resolution_clock` is a count of nanoseconds since the machine booted.  If you don't know when the machine booted, there is just no way to map `high_resolution_clock::now()` back to a calendrical point in time.

**Comment by p-groarke** [comment]
Thanks for clarifying.

For posterity's sake:

I had to convert my `high_resolution_clock` to `system_clock`, which in turns means changing my `time_points` to `dsys_seconds`. `high_resolution_clock` is find with `dseconds` `time_points`, but not `standard_clock`. Once that was done, the following worked as expected.

```c++
using fseconds = std::chrono::duration<float>;
using fminutes = std::chrono::duration<float, std::ratio<60, 1>>;
using fhours = std::chrono::duration<float, std::ratio<3600, 1>>;

using dseconds = std::chrono::duration<double>;
using dminutes = std::chrono::duration<double, std::ratio<60, 1>>;
using dhours = std::chrono::duration<double, std::ratio<3600, 1>>;

using ddays = std::chrono::duration<double, date::days::period>;
using dweeks = std::chrono::duration<double, date::weeks::period>;
using dyears = std::chrono::duration<double, date::years::period>;
using dmonths = std::chrono::duration<double, date::months::period>;

using dsys_days = typename date::sys_time<ddays>;
using dsys_seconds = typename date::sys_time<dseconds>;

// ...

dsys_seconds t = dsys_days(date::sys_days(2020_y / date::jan / 1_d)) + dhours(8);
std::string date_s = date::format("%Y-%m-%d %H:%M", t);
printf("start time : %s\n\n", date_s.c_str());
```

**Comment by HowardHinnant** [comment]
Sounds good.

Fwiw:
```c++

**Comment by p-groarke** [comment]
Nice! Thank you for the advice.
Will you be at cppcon this year? I'd love to say hi :)

**Comment by HowardHinnant** [comment]
I'm afraid I'm going to miss cppcon this year.  I'll be at Meeting C++ in Nov. though.
