### ISSUE TITLE
time difference bug?

### ISSUE THREAD

**Issue by rosshemsley** [HowardHinnant/date#49]
I would like to compute the number of days between 1666-09-02 and 2012-08-01.

With GCC 4.9, I get different answers if one of the arguments is a `chrono::system_clock::time_point`.
Clang works fine. Bug or user error?

```
const auto d1 = day_point(year(1666)/9/2);
const auto d2 = chrono::system_clock::time_point(day_point(year(2012)/8/1));
const auto d3 = day_point(year(2012)/8/1);

cout << "d2 " << d2 << endl << " d1 " << d1 << endl << " d3 " << d3 << endl;
cout << date::days(ceil<date::days>(d1 - d2)).count() << endl;
cout << date::days(ceil<date::days>(d1 - d3)).count() << endl;
```

GCC 4.9 gives me

```
d2 2012-08-01 00:00:00.000000000
d1 1666-09-02
d3 2012-08-01
87162
-126342
```

LLVM 3.6 gives me

```
d2 2012-08-01 00:00:00.000000000
d1 1666-09-02
d3 2012-08-01
-126342
-126342
```

Thanks!

**Comment by HowardHinnant** [comment]
This is an underflow error caused by the fact that on gcc `system_clock::duration` is `nanoseconds` and on llvm `system_clock::duration` is `microseconds`.  On both systems, both `nanoseconds` and `microseconds` have a `rep` equivalent to `int64_t`.  This can be visualized with this program:
````
#include "date.h"
#include <iostream>

int
main()
{
    using namespace std::chrono;
    using namespace date;
    using gcc_time_point = time_point<system_clock, nanoseconds>;
    using llvm_time_point = time_point<system_clock, microseconds>;
    std::cout << gcc_time_point::min() << '\n';
    std::cout << llvm_time_point::min() << '\n';
}
````
which outputs:
````
1677-09-21 00:12:43.145224192
-28164-12-21 19:59:05.224192
````
To fix you could give `d2` type `time_point<system_clock, microseconds>`.

I've hit a similar error when using `minutes`, which on some platforms (VS and llvm 32 bit) is stored with `int32_t`.  A 32 bit based `time_point<system_clock, minutes>` reaches back to `-2114-12-08 21:52:00`.

**Comment by rosshemsley** [comment]
Will switch to seconds instead as that's plenty accurate. Unfortunate that this is platform dependent though, might be nice to have a small note in the docs (unless there is and I missed it)

Thanks for the fast response!
