### ISSUE TITLE
How to use the lib with cmake

### ISSUE THREAD

**Issue by MaximNM** [HowardHinnant/date#506]
I'm not expert in cmake and using the lib following way:

```
find_package(date REQUIRED) 
if(date_FOUND)                                                                                                                      
    message("Howard Hinnant's Date lib found")                                                                                                                                                                           
else()                                                                                                                              
    message(SEND_ERROR "Howard Hinnant's Date not found")                                                                           
    return()                                                                                                                        
endif()   

target_include_directories(${PROJECT_NAME} PUBLIC ${date_INCLUDE_DIRS})

target_link_libraries(${PROJECT_NAME} date::tz)
```

Could somebody recommend the best approach?

**Comment by Erroneous1** [comment]
A big issue with CMake is that you'll find a lot of examples that don't deal with modern (often easier) CMake.

```
#if we're including date as a subproject
add_subdirectory(libs/date)
#otherwise we're looking for an installed lib
#find_package(date REQUIRED)

add_executable(main main.cpp)

target_link_libraries(main PUBLIC date::date)
```
When you link one target to a library target (i.e. one declared with add_library) CMake will automatically sort out any required dependencies and include directories for that linked target. If you include the date library as a subdirectory (by cloning the repo to `libs/date` for instance) then you can configure the library as you want before using `add_subdirectory`:
```
set(USE_SYSTEM_TZ_DB ON)
set(BUILD_TZ_LIB ON)
set(COMPILE_WITH_C_LOCALE ON)
add_subdirectory(libs/date)

target_link_libraries(main PUBLIC date::tz)
```
Adding as a subdirectory has a disadvantage though if you're making a project that could be included as part of a larger project that might also require the date library. If this is the case, you'll want to use `find_package(date REQUIRED)` and document that if the date library must either be installed or the user will need to provide a `Finddate.cmake`.

You can also use the date library that was installed instead of including it as a subdirectory. This is probably NOT going to be your use case, but if you'd like that you can do:
```
find_package(date REQUIRED)
target_link_libraries(${PROJECT_NAME} date::tz)
```

Checking for date_FOUND and issuing an error isn't required because that's what the REQUIRED flag does. Manually including directories is similarly not required because linking to `date::tz` will also include and public include directories for the date::tz target.

**Comment by MaximNM** [comment]
@Erroneous1 Thanks a lot!!!

**Comment by dudantas** [comment]
> A big issue with CMake is that you'll find a lot of examples that don't deal with modern (often easier) CMake.
> 
> ```cmake
> #if we're including date as a subproject
> add_subdirectory(libs/date)
> #otherwise we're looking for an installed lib
> #find_package(date REQUIRED)
> 
> add_executable(main main.cpp)
> 
> target_link_libraries(main PUBLIC date::date)
> ```
> 
> When you link one target to a library target (i.e. one declared with add_library) CMake will automatically sort out any required dependencies and include directories for that linked target. If you include the date library as a subdirectory (by cloning the repo to `libs/date` for instance) then you can configure the library as you want before using `add_subdirectory`:
> 
> ```cmake
> set(USE_SYSTEM_TZ_DB ON)
> set(BUILD_TZ_LIB ON)
> set(COMPILE_WITH_C_LOCALE ON)
> add_subdirectory(libs/date)
> 
> target_link_libraries(main PUBLIC date::tz)
> ```
> 
> Adding as a subdirectory has a disadvantage though if you're making a project that could be included as part of a larger project that might also require the date library. If this is the case, you'll want to use `find_package(date REQUIRED)` and document that if the date library must either be installed or the user will need to provide a `Finddate.cmake`.
> 
> You can also use the date library that was installed instead of including it as a subdirectory. This is probably NOT going to be your use case, but if you'd like that you can do:
> 
> ```cmake
> find_package(date REQUIRED)
> target_link_libraries(${PROJECT_NAME} date::tz)
> ```
> 
> Checking for date_FOUND and issuing an error isn't required because that's what the REQUIRED flag does. Manually including directories is similarly not required because linking to `date::tz` will also include and public include directories for the date::tz target.

This should be added to the project wiki!

**Comment by xsgao-github** [comment]
>You can also use the date library that was installed instead of including it as a subdirectory. This is probably NOT going to be your use case, but if you'd like that you can do:
>
>```
>find_package(date REQUIRED)
>target_link_libraries(${PROJECT_NAME} date::tz)
>```

I installed date by executing `brew install howard-hinnant-date`, I can reference `date::date` but not `date::tz`. `target_link_libraries(${PROJECT_NAME} date::tz)` gave me the following error:

```
CMake Error at CMakeLists.txt:138 (target_link_libraries):
  Target "odbc" links to:

    date::tz

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
