### ISSUE TITLE
apply time zone and DST

### ISSUE THREAD

**Issue by berge2007** [HowardHinnant/date#507]
I have an UTC time_point:
`std::chrono::system_clock::time_point utc_tp; //2019-10-27T00:00:00.123456Z`

I would like to know what is the local time_point in 'London':
`std::chrono::system_clock::time_point london_tp;`

So if I convert
'2019-10-27T00:00:00.123456Z' (UTC) I should get '2019-10-27T01:00:00.123456' (Europe/London)
or
'2019-10-27T01:00:00.123456Z' (UTC) I should get '2019-10-27T01:00:00.123456' (Europe/London, DST ended!) 

I did the following:

```
std::chrono::system_clock::time_point utc_tp; //2019-10-27T00:00:00.123456Z
auto london_zone = date::locate_zone("Europe/London");
auto london_zoned = date::make_zoned(tz, utc_tp);
auto london_local = london_zoned.get_local_time();

std::chrono::system_clock::time_point london_tp = ??? london_local ???
```
but I've stucked at convert `local_time` to `std::chrono::system_clock::time_point`

What would be the most effective way to get local time in time_point?

**Comment by HowardHinnant** [comment]
`local_time` is itself what you want.  It is a `std::chrono::time_point`, but with a distinct "clock" from `system_clock`.  The rationale for this is so that you don't accidentally mix `system_clock::time_point` (which has the semantics of UTC), with `local_time`.

In your example above, you can just stream to `cout` `london_zoned` and you will get the local time in London with the current time zone abbreviation.

You could also stream `london_local`, and you will get the same time as `london_zoned` but without the time zone abbreviation.  `local_time` (`london_local`) represents a "local time" of an _unspecified_ time zone, whereas `zoned_time` (`london_zoned`) represents an absolute instant in time, and can specify that instant either in terms of a `local_time` plus `time_zone`, or as a UTC `sys_time`.

**Comment by berge2007** [comment]
I understand that type safe conception but my codebase based on `system_clock::time_point` (created earlier than I started to use this 'date' lib), so I thought there is an easy way to wandering between the two (local_time vs. local time in system_clock::time_point) time handling conceptions

Bu maybe I should  do some refactoring ... :D

Thank you so much for the speedy reply!

**Comment by HowardHinnant** [comment]
You caught me at an opportune time! :-)

If you find yourself absolutely having to "reinterpret cast" between two families of `time_point`s, then that can be accomplished by converting the source `time_point` to a `duration` with `.time_since_epoch()`, and then converting that `duration` to the destination `time_point` type with explicit construction syntax.  For example:
```
std::chrono::system_clock::time_point london_tp{london_local.time_since_epoch()};
```
I must emphasize that this is a dangerous reinterpret cast, and not recommended.  But I also acknowledge that you know better what has to be done for your application than I do.  So here's the sharp blade. ;-)

**Comment by berge2007** [comment]
I'll spread `date::local_time` throught the codebase but until this is the 'sharpest' way :D
 
Thank you very much!
