### ISSUE TITLE
Why does date::format using seconds conversion specifier add fractional seconds?

### ISSUE THREAD

**Issue by bangusi** [HowardHinnant/date#543]
```
auto local_datetime = date::make_zoned(date::current_zone(), std::chrono::system_clock::now());
std::cout << date::format("%H:%M:%S", local_datetime) << "\n";

```
produces:
16:58:45.2769403
was expecting
16:58:45
like what `std::put_time` does:
```
std::time_t t = std::time(nullptr);
std::tm tm = *std::localtime(&t);
std::cout << std::put_time(&tm, "%H:%M:%S") << '\n';
```

**Comment by HowardHinnant** [comment]
You need to truncate the precision of the `time_point` that you send into format to seconds precision.  That can either be done at the construction of `local_datetime`,

    auto local_datetime = date::make_zoned(date::current_zone(),
         date::floor<std::chrono::seconds>(std::chrono::system_clock::now()));

or at the call to `format`:

    date::format("%H:%M:%S", date::floor<std::chrono::seconds>(local_datetime))

In C++17 and later, `floor` is in namespace std::chrono.  Or since `now()` is known to be a time after the `system_clock` epoch, you can also spell `floor` as `std::chrono::time_point_cast`.

And in general, you can make the output any precision you want by truncating/casting to any precision you want.  `format` will output as many digits as necessary to make an exact textual representation of the input time_point.

**Comment by bangusi** [comment]
Got it, The handling of the seconds specifier is un-expected though.
Common usage is to control formatting through specifiers. 
For example in most databases if I wanted to see fractional seconds I would go
something like this'
`'YYYY-MM-DD HH24:MI:SS.FF';`
if I wanted just seconds
`'YYYY-MM-DD HH24:MI:SS';`
regardless of the input

**Comment by HowardHinnant** [comment]
Yeah.  I made another design choice.
