### ISSUE TITLE
%b notation is case sensitive for gcc 

### ISSUE THREAD

**Issue by niyue** [HowardHinnant/date#550]
I tried to parse a date string like `01/jan/2020:00:00:00 +0000` (notice the lower cased `jan`) with format like `%d/%b/%Y:%H:%M:%S%t%z`. I found it works as expected on Apple Clang (on my macOS) but it doesn't work on gcc (on a Linux container).

Here is a test case I came up with (the result is correct if the compiler is clang but not correct once I switch the compiler to gcc 9.2.0, it could affect more gcc versions):
https://wandbox.org/permlink/tYOIOAqepN8ScYfh

According to the documentation: 
```
%b | The locale's full or abbreviated case-insensitive month name.
```
So I assume the month name should be case-insensitive in this case. Could any one please help? Thanks.

**Comment by HowardHinnant** [comment]
Here is the gcc bug report causing this behavior:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78714

Feel free to comment the bug to let the maintainers know how this bug is impacting you.

Meanwhile you can work around this bug by compiling date.h with `-DONLY_C_LOCALE`.  This tells date.h to not use the `std::time_get` facets for parsing, but instead use a custom parsing algorithm.  The restriction with this flag is that it only works with the "C" locale, and thus won't pick up localized month names.  However it does work with abbreviations and full names, and is case insensitive as noted in the documentation.

**Comment by niyue** [comment]
@HowardHinnant thanks so much for the guidance. 
I will give the compiler flag try. 
Do you think if I need to leave this ticket open or close it since it depends on the fix of gcc eventually?

**Comment by HowardHinnant** [comment]
I'm easy.  The gcc bug has been open for years.  But I have hopes it will get fixed as they implement this library for C++20.  If you leave it open, others might see it more reliably.  However if you leave it open, I might close it one night in a flurry of closing a bunch of issues. :-)

I'm not very good at process, and don't let it bother me much. :-)

**Comment by niyue** [comment]
Let me close it, others will eventually use google to find this closed bug if it really bothers them :)
