### ISSUE TITLE
date::floor does not floor to midnight when flooring year and month.

### ISSUE THREAD

**Issue by H-Matthew** [HowardHinnant/date#551]
If I have a time set to roughly 2020/03/06 11:11:12.0000000 then I get the following results.

system_clock::time_point T1 = date::floor\<months\>(time) = 2020/03/01 23:58:12.0000000
system_clock::time_point T2 = date::floor\<days\>(date::floor\<months\>(time)) = 2020/03/01 00:00:00.0000000
system_clock::time_point T3 = date::floor\<days\>(time) = 2020/03/06 00:00:00.0000000

So I cannot compare things like T1 + days(5) == T3 though T2 + days(5) == T3 works because of the floor\<days\>. If I use floor\<years\> I have the same problems as floor\<months\> but the time portion of the date and time is different to if it was floored to months. I'm using date::format("%Y/%m/%d %H:%M:%S", time) for output.

Is there something I'm doing wrong?

**Comment by HowardHinnant** [comment]
This library makes a distinction between _chronological_ computations and _calendrical_ computations.  For units such as `days`, there is no distinction (until you get into time zones anyway).  But for units such as `months` and `years`, the distinction is more apparent because these units have different meanings in _chronological_ computations and _calendrical_ computations.

Here is a SO answer that goes into great detail about how to add months to a date.  There's no one right way to do it, and this library allows you to perform which ever way is right for you:

https://stackoverflow.com/a/43018120/576911

In your case, it appears you want to find the first of the month given a `system_clock::time_point` with a value of 2020/03/06 11:11:12.0000000.  `floor<months>(time)` takes the time duration since the Unix epoch (1970-01-01 00:00:00 UTC) and divides it by the _average_ civil month length:  2629746s or 30d 10:29:06.  This is a _chronological_ computation and is appropriate for modeling physical processes that don't care about the irregularities in calendrical systems.  It does not preserve things such as time-of-day, or even day-of-month.

To find the first instant of a month, one must first convert from the chronological system (`system_clock::time_point`) to a calendrical system (`year_month_day`), and then do the computation in the calendrical system.  Then (optionally) convert back into the chronological system:

```c++
    // The chronological system
    system_clock::time_point time = sys_days{2020_y/03/06} + 11h + 11min + 12s;

    // Convert time into a calendrical system
    year_month_day ymd = floor<days>(time);

    // Find the first day of the month of ymd, and convert it back
    // into the chronological system
    system_clock::time_point T1 = sys_days{ymd.year()/ymd.month()/1};

    system_clock::time_point T3 = floor<days>(time);
    cout << T1 << '\n';
    cout << T3 << '\n';
    cout << T1 + days{5} << '\n';
```

Output:

```
2020-03-01 00:00:00.000000
2020-03-06 00:00:00.000000
2020-03-06 00:00:00.000000
```

**Comment by H-Matthew** [comment]
Ah it's like that. Thank you for such an informative answer. I had totally expected floor for years, months and days to floor to midnight discarding the time of day completely. I guess I just have to use year_month_day. I wondered why bother with that type if you could calculate that information from time_point but it makes sense now. Thanks again.
