### ISSUE TITLE
Parsing milliseconds of last second in minute failing

### ISSUE THREAD

**Issue by vovo-4K** [HowardHinnant/date#663]
If the fractional part in the last second of minute (e.g. 59) is above 0.5 then date::parse is unable to parse the string.

The code to reproduce: (link to [Wandbox](https://wandbox.org/permlink/YEVio9i4MJnbcx3O) )
```c++
#include "date.h"
#include <iostream>
#include <vector>

bool isParsed(const std::string& time_str)
{
    std::istringstream time_ss(time_str);

    date::sys_seconds tp;
    time_ss >> date::parse("%H:%M:%0S %F", tp);

    return !time_ss.fail();
}

int
main()
{
    using namespace date;
    using namespace std;
    using namespace std::chrono;

    std::vector<std::string> time_to_parse =
    {
        "00:00:49.500 1970-01-01", // ok
        "00:00:58.500 1970-01-01", // ok
        "00:00:59 1970-01-01", // ok
        "00:00:59.000 1970-01-01", // ok
        "00:00:59.499 1970-01-01", // ok
        "00:00:59.500 1970-01-01", // fault
        "00:00:59.600 1970-01-01", // fault
        "00:00:59.999 1970-01-01", // fault
        "00:01:00.000 1970-01-01" // ok
    };
    
    for(const auto &time_str : time_to_parse)
    {
        std::cout<<"parsing '"<< time_str << "' : "<< (isParsed(time_str) ? "ok" : "fault") << std::endl;
    }

    return 0;
}
```

The used compiler doesn't matter.

**Comment by HowardHinnant** [comment]
The width specifier on `%NS` must be positive.  The value of `N` specifies the maximum number of characters to read while parsing the seconds.  This count includes the integral part, the decimal point, and the fractional part.  It is ok, if fewer characters are read.

The effect of specifying 0 is undefined.  But in this case has the behavior of specifying an unlimited width.  That in itself is not a problem.  The real problem is that after reading the seconds, the parser **rounds** the parsed value to the requested precision (milliseconds to seconds in this example).  The round-to-nearest behavior is required to support precisions that can't be exactly represented in a finite number of decimal digits (e.g. `duration<int, ratio<1, 3>>`).

When the rounded result is outside of the range [0, 60), then failbit is set.  And in this example, the rounded result is 60s.

The fix for both of these problems is to omit the width specifier and parse into a milliseconds-precision time_point:
```c++
    date::sys_time<std::chrono::milliseconds> tp;
    time_ss >> date::parse("%H:%M:%S %F", tp);
```
If you absolutely must specify a width, specify 6:
```c++
    date::sys_time<std::chrono::milliseconds> tp;
    time_ss >> date::parse("%H:%M:%6S %F", tp);
```
If you must have seconds-precision, then truncate it after the parse:
```c++
    date::sys_time<std::chrono::milliseconds> tp_ms;
    time_ss >> date::parse("%H:%M:%S %F", tp_ms);
    auto tp = floor<seconds>(tp_ms);
```

**Comment by vovo-4K** [comment]
Thank you for the detailed reply! I think I was confused with option %OS, but used %**0**S instead.

Using time_point with date::sys_time<std::chrono::milliseconds> fixes the problem.
