### ISSUE TITLE
Parsing failure when `59.500` and above are rounded to seconds

### ISSUE THREAD

**Issue by DavisVaughan** [HowardHinnant/date#667]
The following:

```c++
#include <sstream>
#include <iostream>
#include "date/date.h"

void test_rounding() {
  using namespace date;

  // Bad - Rounds up to "invalid" 60 seconds
  sys_seconds tp1{};
  std::istringstream x1{"2021-04-16T22:35:59.500Z"};
  x1 >> parse("%Y-%m-%dT%H:%M:%6SZ", tp1);
  std::cout << tp1 << std::endl;

  // Good - Rounds down to 59 seconds
  sys_seconds tp2{};
  std::istringstream x2{"2021-04-16T22:35:59.499Z"};
  x2 >> parse("%Y-%m-%dT%H:%M:%6SZ", tp2);
  std::cout << tp2 << std::endl;
}
```

Outputs:

```
1970-01-01 00:00:00
2021-04-16 22:35:59
```

`59.500` is rounded up to `60` here
https://github.com/HowardHinnant/date/blob/6e921e1b1d21e84a5c82416ba7ecd98e33a436d0/include/date/date.h#L7263

Then the `fds.tod.in_conventional_range()` condition returns `false` here, so it looks invalid
https://github.com/HowardHinnant/date/blob/6e921e1b1d21e84a5c82416ba7ecd98e33a436d0/include/date/date.h#L8011

**Comment by HowardHinnant** [comment]
Agreed.

**Comment by HowardHinnant** [comment]
Sorry I wasn't clear.

Your description of the current behavior didn't state a complaint or an expected behavior.  I agreed that this is the current behavior.

It is intended that parsing something that results in `sys_days{2016_y/12/11} + seconds{60}` set `failbit` since 2016-12-11 00:00:60 does not exist on the civil calendar associated with `sys_time`.

The correct way to parse this is to parse into `sys_time<milliseconds>`, and then truncate that result into `sys_seconds` after the parse using whichever rounding mode is desired:  `time_point_cast`, `floor`, `ceil`, or `round`.

If the input stream has varying precision time stamps, one should use the highest precision of all the time stamps (`sys_time<nanoseconds>` is the finest practical time stamp).  The parsing function will properly deal with this if there exist fewer than 9 fractional decimal digits.

The rationale for not supporting reading into types with coarser precision is that the parser should not presume the rounding direction desired by the client.  The client should do such rounding himself after the parse completes.  Internally, `round` is used only so that the correct value is parsed when parsing into units which can not be represented by a finite number of decimal digits (e.g. `sys_time<duration<int, ratio<1, 3>>>`).

For the client that needs to parse fractional seconds, but store them into seconds, round to nearest may not be desirable, and even if it is, he may consider anything over 59s a parse error.  The only way to truly handle every use case is to encourage the client to perform an exact parse and do the truncation afterwards.

Indeed, without the rather unusual step of adding the width specifier: `%6S`, this parse would naturally fail.  The corrective action should be to parse into `sys_time<milliseconds>` instead of add the `6` to `%S`.

**Comment by DavisVaughan** [comment]
> I agreed that this is the current behavior.

Ah I took that as agreement that this was a bug (which I agree I wasn't clear about either).

---

For some context, R's native date-time type only has second precision, but users often have time stamps containing fractional seconds that they need to parse anyways. In clock, the best way for them to deal with this is to instead use a clock type that can handle fractional seconds, but I try to be lenient by providing a parser that goes directly into R's date-time type too, rounding to second automatically as required.

Currently, that works by parsing directly into `local_seconds` as the intermediate result, which is then converted to R's date-time type. If users have fractional seconds, this currently requires them to use `%NS` for it to even parse, which is where this came from.

Based on your comments, I think I'll change it to parse into `local_time<microseconds>` and give the user the option of cast/floor/ceiling/round for when the truncation happens. That should give me enough range to still cover R's date-time limits, around +/-9999 years, and `%S` should sort of "just work" for up to microsecond fractional seconds (by "work", I mean that it will parse without extra effort, then be truncated somehow). I'll just document that if they want to keep the fractional seconds, or if for some reason they are trying to push nanoseconds through this, they should use a proper clock type that can support it.

---

> Internally, round is used only so that the correct value is parsed when parsing into units which can not be represented by a finite number of decimal digits (e.g. sys_time<duration<int, ratio<1, 3>>>).

The fact that this is really the _only_ accepted reason for the internal rounding is something I didn't quite understand. At the time, it seemed like a more general feature to me.

**Comment by DavisVaughan** [comment]
Hi @HowardHinnant, I was thinking about this a little more and have one more follow up question.

When do you imagine the `N` command of `%NS` being used? Is it only for compatibility with units which can not be represented by a finite number of decimal digits (e.g. the `sys_time<duration<int, ratio<1, 3>>>` you mentioned above?).

At first I thought it was exactly for the case when you had a string with fractional seconds, and wanted to read it into a coarser type, but then you mentioned:

> not supporting reading into types with coarser precision

so I no longer think that is the case. Which left me wondering when it is intended to be used at all.

Thanks!

**Comment by HowardHinnant** [comment]
`N%S` comes in handy when you've got a seconds with "too many" leading zeroes.  For example "007".  The default only permits one leading zero.

**Comment by ecorm** [comment]
I'm learning the hard way that this library unfortunately doesn't follow the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle) when it comes to parsing: "be conservative in what you send, be liberal in what you accept".

To be fair, it does give you the building blocks to implement your own, more liberal parsing.

**Comment by ecorm** [comment]
My previous comment may have sounded rather harsh; I apologize. I'm sure there are some who like/need the current strict seconds parsing. But it would be nice if there were also something like a new `%ES` parsing flag that consumed as many digits as possible and `floor`ed the result into the destination time/duration type.
