### ISSUE TITLE
Convert from a timezone to utc

### ISSUE THREAD

**Issue by hrkalona** [HowardHinnant/date#669]
I have some implementation like this which get a timestamp as an input which will be on a specific timezone (tz) and I want to convert to UTC. What should I do?
I have already created the opposite case (timestamp on utc and I have to convert it to tz)

  DateTime TZConv::Convert(bool toUTC, const DateTime& dt, const Str& tz)
        {
            if (toUTC) {
                
            }
            else {
                const auto converted = date::make_zoned(tz.c_str(), system_clock::from_time_t(dt.toTimeT()));
                return DateTime(converted.get_local_time().time_since_epoch().count() / 10000000); 
            }
        }

**Comment by hrkalona** [comment]
I refactored it like this for now:

if (toUTC) {
        const auto converted = date::make_zoned(tz.c_str(), system_clock::from_time_t(dt.toTimeT()));
        return DateTime(floor<seconds>(converted.get_sys_time()).time_since_epoch().count());
    }
    else {
        const auto converted = date::make_zoned(tz.c_str(), system_clock::from_time_t(dt.toTimeT()));
        return DateTime(floor<seconds>(converted.get_local_time()).time_since_epoch().count());
    }

but in my example I pass a datetime of 2021-05-06 11:19:30, toUTC = true, and tz = Europe/Bucharest,
in theory I should get 2021-05-06 08:19:30 as a result but I am still getting 2021-05-06 11:19:30, which is my original input

**Comment by hrkalona** [comment]
My end result is to convert the timestamp from timezone tz to UTC

**Comment by hrkalona** [comment]
Ok just a final question then, I have a time_t holding my datetime how do I convert it to local_seconds?

**Comment by hrkalona** [comment]
Ok, just a final question then, my timestamp is in time_t how do I convert it to date::local_time so I can use it in zoned_time?

**Comment by hrkalona** [comment]
I tested some of the example you posted, but I am getting these errors:
![image](https://user-images.githubusercontent.com/1044172/117784006-c1e16e80-b24b-11eb-8148-c22f9ae46c02.png)

**Comment by HowardHinnant** [comment]
From your comments I'm presuming:

1.  You are using C++11 or C++14.  This explains the error message about not deducing the template parameters for `zoned_time`.  And in that case, yes, the use of `make_zoned` is a reasonable workaround.
2.  Your `time_t` is holding a count of seconds since 1970-01-01 00:00:00 _in your local time zone_.  This is highly unusual as most platforms have `time_t` hold a count of seconds since 1970-01-01 00:00:00 UTC.  However, if it is working for you, then that's great.

If my assumptions are correct, here is an equivalent, and somewhat simplified rewrite for the line of code that constructs `converted`:

```c++
const date::zoned_seconds converted{tz.c_str(),
          date::local_seconds{std::chrono::seconds{dt.toTimeT()}}};
```

Comments:
1.  There exists a type alias `zoned_seconds` which is equivalent to `zoned_time<seconds>`, which is the type `make_zoned` returns when its argument as seconds-precision.
2. There is a type alias `local_seconds` which is equivalent to `local_time<seconds>`.  Saves a little on typing.
3. Assuming `dt.toTimeT()` is returning an integral count of seconds since the _local_ epoch, this simply converts that integer to `seconds`, and then to `local_time<seconds>` and uses it.  No need to make the trip through `system_clock::from_time_t`.  If `dt.toTimeT()` is returning an unsigned integral, you'll need to use `()` instead of `{}` for the `seconds` constructor.

**Comment by hrkalona** [comment]
Yes your assumptions are corrected, your refactor worked like a charm!
I had to modify the internals a little bit since I was passing a windows timezone as tz, and the internal mapping was not used.

I modified tzdb::locate_zone(std::string_view tz_name) const and I added this:

#if HAS_STRING_VIEW
    std::string_view mapped;
#else
    std::string mapped;
#endif

    if (native_to_standard_timezone_name(tz_name, mapped))
    {
        tz_name = mapped;
    }

as a quick workaround.

I see that your are using native_to_standard_timezone_name only when you are converting a current zone in windows.
In my implementation I need to converted any windows zone to utc and vice versa.

**Comment by hrkalona** [comment]
I had to create an overloaded native_to_standard_timezone_name for string_view but it works for now

**Comment by hrkalona** [comment]
Also, if mappings are sorted by the window's key then we can do a lower_bound  search instead of linear search

**Comment by hrkalona** [comment]
Thank you very much for your help!
