### ISSUE TITLE
Unable to `parse` the time zone information correctly

### ISSUE THREAD

**Issue by akalsi87** [HowardHinnant/date#691]
Hi Howard,

I'm trying to parse a datetime string to a datetime:

```c++
#include <date/date.h>

#include <chrono>
#include <iostream>
#include <sstream>
#include <utility>

using namespace date;

template <class DUR>
auto tryParse(std::stringstream& stream, std::string fmt, const std::string& str) -> std::pair<sys_time<DUR>, bool> {
    sys_time<DUR> out;
    stream.clear();
    stream.str(str);

    stream >> parse(fmt.c_str(), out);
    
    bool ok{true};
    if (stream.fail() ||
        stream.get() != std::stringstream::traits_type::eof()) {
        ok = false;
    }
    return std::make_pair(out, ok);
}

int main() {
    std::stringstream stream;
    auto out = tryParse<std::chrono::microseconds>(stream, "%Y-%m-%d %H:%M:%S %Z", "2021-08-06 16:01:44.424348 EDT");
    std::cout << out.first << std::endl;
    return !out.second;
}
```

I see incorrect values print back, and am wondering what I did wrong.  My understanding is that the `sys_time` should be adjusted for the specified TZ.

actual = 2021-08-06 16:01:44.424348 UTC
expected = 2021-08-06 20:01:44.424348 UTC

I'm also confused as to why the `parse` function does not take advantage of `tz.h` if it is available?  In case it does and I missed it, I am using `AUTO_DOWNLOAD = 1` and `USE_REMOTE_API = 1`.

**Comment by HowardHinnant** [comment]
Unfortunately there is no reliable way to turn a time zone abbreviation (EDT) into a time zone, or UTC offfset.  Here's a more indepth article on that:  https://github.com/HowardHinnant/date/wiki/Examples-and-Recipes#convert_by_timezone_abbreviation

One way to parse this is to change `sys_time<DUR> out;` to `local_time<DUR> out;` and then at least you will have the right value in the right type:  `out == 2021-08-06 16:01:44.424348`.  But that still leaves you with an unknown UTC offset, unless you can add some logic that maps EDT to -4h.

If the input string contained the offset, then it can be parsed with `%z` or `%Ez`, and then that offset would be automatically applied when the time point type is `sys_time`.

If the input string contained the name of the time zone, instead of the abbreviation, then that can be use to recover the UTC offset like this:

```c++
template <class DUR>
auto
tryParse(std::stringstream& stream, std::string fmt, const std::string& str)
    -> std::pair<sys_time<DUR>, bool>
{
    local_time<DUR> out;
    stream.clear();
    stream.str(str);

    std::string time_zone_name;
    stream >> parse(fmt.c_str(), out, time_zone_name);
    
    bool ok{true};
    if (stream.fail() ||
        stream.get() != std::stringstream::traits_type::eof()) {
        ok = false;
    }
    zoned_time zt{time_zone_name, out};
    return std::make_pair(zt.get_sys_time(), ok);
}

int main() {
    std::stringstream stream;
    auto out = tryParse<std::chrono::microseconds>(stream, "%Y-%m-%d %H:%M:%S %Z",
                                                   "2021-08-06 16:01:44.424348 America/New_York");
    std::cout << out.first << std::endl;
    std::cout << out.second << std::endl;
}
```
Output:
```
2021-08-06 20:01:44.424348
```

**Comment by akalsi87** [comment]
Makes sense.  Sorry that I did not review the wiki pages. Is it possible then to throw an exception or provide other feedback that this conversion was not successful?

**Comment by HowardHinnant** [comment]
Success is in the eye of the client here.  You can check the value of the abbreviation if you want, and then take whatever action you deem appropriate:

```c++
std::string abbrev;
stream >> parse(fmt.c_str(), out, abbrev);
if (abbrev != "UTC")
   throw ...
```

**Comment by HowardHinnant** [comment]
My full example above throws an exception if it can't find `time_zone_name` in the database.  This happens under the `zoned_time` constructor.
