### ISSUE TITLE
Correct TAI with a leap smear server

### ISSUE THREAD

**Issue by pawnissimo** [HowardHinnant/date#701]
If the system clock is based on a server implementing a leap second smear, how would I go about getting the exact/unsmeared TAI (or UTC) time when calling tai_clock::now().

**Comment by HowardHinnant** [comment]
As implemented, `tai_clock::now()` will be correct (to within your computer's clock precision), except during a leap second smear.  This is because `tai_clock::now()` is implemented in terms of `system_clock::now()`.

However, if you had access to a better source of time (an atomic clock, a gps reciever, etc.), you could reimplement `tai_clock::now()` to access this superior source of correct time.  If you did so, you could also reimplement all of the other clocks in terms of this superior source of time.  E.g. `utc_clock::now()` could call `tai_clock::now()`.

Convenience link: https://github.com/HowardHinnant/date/blob/master/include/date/tz.h#L2099-L2104

It is important to understand that this library doesn't turn your computer into a super accurate clock.  It just provides a framework that makes it easier to plug into a superior clock should one be available.  As implemented out of the box, the only portable source of time is `system_clock::now()` provided by your OS.
