### ISSUE TITLE
How to check the validity of a date?

### ISSUE THREAD

**Issue by pawnissimo** [HowardHinnant/date#705]
How would I go about checking if a date is valid?

For instance how can I detect that these dates are invalid:

// 2021 is not a leap year
local_days d = local_days{year(2021)/month(2)/day(29)};

// September 31st does not exist
local_days d = local_days{year(2021)/month(9)/day(31)};

**Comment by HowardHinnant** [comment]
Under the hood `local_days` is nothing but a count of days since (or prior for negative values) 1970-01-01.  Because of this representation `{count}`, _all_ values of `local_days` are valid dates.

However in a `{year, month, day}` data structure, it is possible that the combination of values results in an invalid date, e.g. 2021-09-31.  In order to catch such a date, you must check it while in the `{year, month, day}` data structure.  This structure is named `year_month_day`.

The `year_month_day` type has a member function: `.ok()` which returns true if the date is valid, and otherwise false.  Checking it might look like:

```c++
auto ymd = year(2021)/month(9)/day(31);  // ymd has type `year_month_day`
if (!ymd.ok())
    // take some corrective action
local_days d{ymd};
// ...
```

**Comment by pawnissimo** [comment]
Thanks a lot!
