### ISSUE TITLE
Why does the from_stream second formatting not support partial seconds?

### ISSUE THREAD

**Issue by liam-reduktive** [HowardHinnant/date#772]
Hi there,

Thanks for the awesome library.

I want to parse an xs:DateTime and the seconds component can contain picosecond resolution with up to 12 digits after an optional decimal point. The to_stream formatting supports partial seconds but the from_stream formatting doesn't seem to do so. Is there a workaround for this?

Many thanks.

**Comment by HowardHinnant** [comment]
Is there a signed 128 bit integral type on your platform?  For example I have `__int128_t`.  And if so, does it have a `operator<<` for it?  Mine does not, but I can show you how to write one in that case.

If there isn't a signed 128 bit integral type, boost might help, but I don't have that worked out.

**Comment by HowardHinnant** [comment]
On macOS I use `__int128_t` to form `picoseconds`.  I have to supply my own streaming operator to print it out.  But then things just work:

```c++
#include <ostream>

namespace std
{

template <class CharT, class Traits>
basic_ostream<CharT, Traits>&
operator<<(basic_ostream<CharT, Traits>& os, __uint128_t u)
{
    char buf[40]{};
    auto p = &buf[0];
    do
    {
        *p++ = static_cast<char>((u % 10) + '0');
        u /= 10;
    } while (u != 0);
    std::reverse(buf, p);
    return os << buf;
}

template <class CharT, class Traits>
basic_ostream<CharT, Traits>&
operator<<(basic_ostream<CharT, Traits>& os, __int128_t i)
{
    char buf[41]{};
    auto p = &buf[0];
    const auto neg = i < 0;
    if (neg)
    {
        *p++ = '-';
        i = -i;
    }
    auto u = static_cast<__uint128_t>(i);
    do
    {
        *p++ = static_cast<char>((u % 10) + '0');
        u /= 10;
    } while (u != 0);
    std::reverse(buf + neg, p);
    return os << buf;
}

}  // namespace std

#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace std;
    using namespace chrono;
    using namespace date;

    istringstream in{"2023-01-25T12:00:00.123456789012"};
    in.exceptions(ios::failbit);
    using picoseconds = duration<__int128_t, pico>;
    sys_time<picoseconds> tp;
    in >> parse("%FT%T", tp);
    cout << tp << '\n';
}
```
Output:
```
2023-01-25 12:00:00.123456789012
```

If you don't have a 128 bit type, things get much harder.  I attempted to use `boost::multiprecision::int128_t` but it didn't work out.  I think it was a lack of support for `std::common_type`, and interoperability with `long double`.

**Comment by liam-reduktive** [comment]
Thank you for the quick response!

I’m a little confused because you are discussing output, but my requirement is to parse a value from a string.

I only need to parse the value to 100ns precision as I’m converting an xs:DateTime to Windows fileTime. Does this make it easier? The from_stream format specifier documentation doesn’t say anything about being able to parse a non-integer seconds field.

Thanks again.

**Comment by HowardHinnant** [comment]
`date::parse` used above is a slightly higher level API but otherwise equivalent to the `date::from_stream` function you referenced.  Either could be used here.  It is parsing from the `istringstream`.  To use `from_stream` replace this line:

```c++
    in >> parse("%FT%T", tp);
```

with:

```c++
    from_stream(in, "%FT%T", tp);
```
But as you're on Windows, no 128 bit integer to work with anyway.

I recommend you parse into a nanoseconds precision time_point, and do an extra parse to clean out the last 3 digits (if desired).  Then round the time point to Windows precision.  Then to get a fileTime as an `int64_t`, add the Windows file time epoch.  Maybe something like:

```c++
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace std;
    using namespace chrono;
    using namespace date;

    // parse into sys_time<nanoseconds>
    istringstream in{"2023-01-25T12:00:00.123456789012"};
    in.exceptions(ios::failbit);
    sys_time<nanoseconds> tp;
    int left_over_digits;
    in >> parse("%FT%T", tp) >> left_over_digits;

    // round to 100ns precision
    using decimicroseconds = duration<int64_t, ratio<1, 10'000'000>>;
    auto rounded_tp = round<decimicroseconds>(tp);
    cout << rounded_tp << '\n';

    // Convert to Windows fileTime epoch
    constexpr auto file_time_epoch = sys_days{} - sys_days{1601_y/1/1};
    int64_t fileTime = (rounded_tp - sys_days{} + file_time_epoch)/decimicroseconds{1};
    cout << fileTime << '\n';
}
```

Output:
```
2023-01-25 12:00:00.1234568
133191216001234568
```

**Comment by liam-reduktive** [comment]
Perfect. Thanks so much for your guidance Howard. It’s really appreciated!

**Comment by HowardHinnant** [comment]
I know this is closed but a much cleaner solution occurred to me.  My existing solution above has a bug that if there are less than 10 fractional seconds digits, the parse of `left_over_digits` might consume some other numerical field by accident, or set failbit by accident if the next non-whitespace is not a digit.

Instead I propose that one parse the entire input stream into a `{sys_time<minutes>, picoseconds}` where the second field holds up to 59.999'999'999'9999 seconds.  This is well within the range of a 64-bit picoseconds unit.

```c++
#include "date/date.h"
#include <iostream>
#include <sstream>

int
main()
{
    using namespace std;
    using namespace chrono;
    using namespace date;
    using decimicroseconds = duration<int64_t, ratio<1, 10'000'000>>;
    using picoseconds      = duration<int64_t, pico>;

    // parse into {sys_time<minutes>, picoseconds} where the second
    // field holds only up to 59.999... seconds
    istringstream in{"2023-01-25T12:00:00.123456789012"};
    in.exceptions(ios::failbit);
    sys_time<minutes> tp;
    picoseconds sec;
    in >> parse("%FT%H:%M:", tp) >> parse("%S", sec);
    cout << "Exact time_point       : " << format("%F %H:%M:", tp)
                                        << format("%S", sec) << '\n';

    // round to 100ns precision
    auto rounded_tp = tp + round<decimicroseconds>(sec);
    cout << "Rounded time_point     : " << rounded_tp << '\n';

    // Convert to Windows fileTime epoch
    constexpr auto file_time_epoch = sys_days{} - sys_days{1601_y/1/1};
    int64_t fileTime = (rounded_tp - sys_days{} + file_time_epoch)/decimicroseconds{1};
    cout << "Windows FileTime count : " << fileTime << '\n';
}
```
Output:
```
Exact time_point       : 2023-01-25 12:00:00.123456789012
Rounded time_point     : 2023-01-25 12:00:00.1234568
Windows FileTime count : 133191216001234568
```

I think this is a much better way to do it, as it will handle a number of fractional digits in the range [0 .. 12].  The one thing to be careful with is to never add `sec` (`picoseconds`) directly to a `sys_time` because you'll get overflow.  You have to truncate it to coarser units first (at least `nanoseconds`).  I've truncated it directly to the Windows precision with `round`.

**Comment by liam-reduktive** [comment]
And how do we handle the case where we have a timezone field such as "<TestData>2009-10-10T12:11:12-05:30" or "2009-10-10T17:00:00.1234567891234Z"? Thanks.

**Comment by HowardHinnant** [comment]
Normally, if you don't have to split the parse because you don't need picosecond precision, you can just add the format `%Ez` to your format string to match the offset, and it will be automatically subtracted from the parsed time (when the type of the argument is a `sys_time`).  However for that to work, the time_point and the offset have to be processed in the same parse, which is not the case for the "split" technique above.

Never worry.  This library is like Leggo building blocks for date/time manipulation.

One can parse the UTC offset with the picoseconds parse and then manually subtract it from your `time_point` like this:

```c++
    istringstream in{"2009-10-10T17:09:01.12345678+10:00"};
    sys_time<minutes> tp;
    picoseconds sec;
    minutes offset;
    in >> parse("%FT%H:%M:", tp) >> parse("%S%Ez", sec, offset);
    tp -= offset;
```

In the second `parse`, the `%S` loads `01.12345678` into `sec` and `+10:00` into `offset`.  So when you print it out as before you get 10h earlier: `2009-10-10 07:09:01.123456780000`.

For handling the trailing `Z`, just add that to the second parse:

```c++
    in >> parse("%FT%H:%M:", tp) >> parse("%SZ", sec);
```

If you don't know before hand which format you're about to parse, you can try multiple formats, check for `in.fail()`, after each one, and if true, try the next format.  Here's an SO answer demonstrating that technique:  https://stackoverflow.com/a/38839725/576911

**Comment by liam-reduktive** [comment]
Perfect thanks!

**Comment by liam-reduktive** [comment]
One small point of interest...

Regarding "constexpr auto file_time_epoch = sys_days{} - sys_days{1601_y/1/1};". My compiler says "non-constexpr function "operator time_point" cannot be used in a constant expression".

**Comment by HowardHinnant** [comment]
Sounds like you're in C++11.  You'll need to change `constexpr` to `const` and this will cause some computation to be shifted from compile-time to run-time.  Not a huge deal, but the more computation at compile-time the better for performance.  There will be no change in the result.

**Comment by liam-reduktive** [comment]
Should be C++17 if CMAKE is behaving itself...

**Comment by HowardHinnant** [comment]
The problem with CMake is that it is so complicated one never knows what it is doing.  So far the code described in this issue only uses date.h.  This is a header-only library that should fit into whatever build system the rest of your code is using.

This could also be due to a compiler that simply hasn't yet implemented C++14 constexpr rules.  date.h does this:

```c++
#  if _MSC_VER < 1910
//   before VS2017
#    define CONSTDATA const
#    define CONSTCD11
#    define CONSTCD14
#    define NOEXCEPT _NOEXCEPT
#  else
//   VS2017 and later
#    define CONSTDATA constexpr const
#    define CONSTCD11 constexpr
#    define CONSTCD14 constexpr
#    define NOEXCEPT noexcept
#  endif
```

I.e. it doesn't "turn on" constexpr until VS2017 / _MSC_VER >= 1910.
