### ISSUE TITLE
One sample outputs unexpected result

### ISSUE THREAD

**Issue by mashoujiang** [HowardHinnant/date#786]
I am testing some examples with latest version of this date library, one simple example is below:
`auto ymdhms0 = sys_days{2014_y/6/1} + hours{18} + minutes{20} + seconds{20};`
`std::cout << ymdhms0 << std::endl;`
`auto ymdhms1 = ymdhms0 + years{1};`
std::cout << ymdhms1 << std::endl;`
`
It outputs:
`2014-06-01 18:20:20`
`2015-06-02 00:09:32`

What happened? should I expect the output be `2015-06-01 18:20:20`? or how could I get the expected output?

Thanks!

**Comment by HowardHinnant** [comment]
This library allows you to do two types of arithmetic with months and years:

1.  Chronological arithmetic.
2. Calendrical arithmetic.

Chronological arithmetic is the addition/subtraction of regular units of time.  Each unit has the same length.  Examples include adding 5 seconds, 5 minutes or 5 hours.  One can even do this with months and years, even though not all years and months have the same length.

If you are dealing with some physical process that doesn't care about human-made calendars, a chronological computation on the order of years may be appropriate.  Just add "average years".  For example the half life of cobalt-60 is about 5 years.  For the purposes of this computation, one can easily and quickly add 5 regular units of `years` to `system_clock::now()` with:

```c++
auto tp = system_clock::now() + years{5};
```

Each unit of `years` models the average length of a year in the civil calendar which turns out to be 365.2425 days.  And this is the computation performed in your example code.  It does not (in general) conserve "time of day" or even "day of year", though on average it is perfectly accurate.

To perform a calendrical computation using a chronological type such as `sys_seconds` (as in your example), the steps are:

1.  Convert the chronological type to a calendar (usually the civil calendar, but doesn't have to be).
2. Perform the arithmetic in the calendrical system.
3. Convert the result back to the chronological type.

Example:

```c++
auto tp_s0 = sys_days{2014_y/6/1} + hours{18} + minutes{20} + seconds{20};
std::cout << tp_s0 << std::endl;

// record the time of day
auto tpd = floor<days>(tp_s0);
auto time_of_day = tp_s0 - tpd;

// convert to a calendrical type
year_month_day ymd = tpd;

// do the arithmetic
ymd += years{1};
// Optionally add logic for overflowing the day field, only if desired
// This will snap Feb 29 back to Feb 28 when necessary.
// If omitted Feb 29 will roll over into Mar 1 when necessary.
// You get to decide what calendrical behavior you want
if (!ymd.ok())
    ymd = ymd.year()/ymd.month()/last;

// convert back to the chronological type, recovering the time of day
auto tp_s1 = sys_days{ymd} + time_of_day;
std::cout << tp_s1 << std::endl; 
```

Output:
```
2014-06-01 18:20:20
2015-06-01 18:20:20
```

One should think of `sys_days` and `year_month_day` as two parallel date types.  Each is perfectly capable of representing a date.  And either can be converted to the other.  They are just two different data structures for the same idea.  But each has advantages and disadvantages.

`sys_days` is very good at day arithmetic, chronological arithmetic, and converting to/from datetimes such as `sys_seconds`.

`year_month_day` is very good at year and month calendrical arithmetic, and for accessing the year, month and day fields.

You should choose your data structure to optimize the performance of your code, much like you choose your container type (vector vs list, etc.).

Here is a SO answer that discusses this same principle but focuses on months instead:  https://stackoverflow.com/a/43018120/576911

**Comment by mashoujiang** [comment]
Thank you so much for this quick and detailed answer! That exactly solves my problem, I will close it.
