### ISSUE TITLE
Should literals be within a separate namespace?

### ISSUE THREAD

**Issue by ecorm** [HowardHinnant/date#9]
Should the `_y` and `_d` literals be within a separate namespace, like the ones for `std::chrono`? The ones for chrono are in `std::literals::chrono_literals`.

I think the main motivation for a separate namespace, is that it allows one to make literals directly visible, without having to make the entire library directly visible:

```c++
using namespace date::date_literals;
date::year year = 2015_y;
```

**Comment by HowardHinnant** [comment]
That's a good suggestion.

**Comment by HowardHinnant** [comment]
Done.  I put namespace `date_literals` at the top level so that you can say:
````
using namespace date_literals;
auto year = 2015_y;
````
But it is connected the same way the std does for `chrono`, so that you can also say:
````
using namespace date;
auto year = 2015_y;
````
I also put the `constexpr` "literals" in `date_literals` such as `sun`, `jan` and `last`.
https://github.com/HowardHinnant/date/commit/6af1976e368cf1cfe883aae701aae9ddf7f3a5f6
