### ISSUE TITLE
Cannot stream out a sys_seconds

### ISSUE THREAD

**Issue by iliocatallo** [HowardHinnant/date#90]
Hi,

After obtaining a valid `date::sys_seconds` as a result of calling `date::parse` I would like to take advantage of the overloaded `operator<<` as defined in `date.h`:

```cpp
date::sys_seconds tp;
date::parse(sstream, "%Y-%m-%d %H:%M:%S", tp);	 
std::cout << tp << std::endl;
``` 

Unfortunately, both g++ 6 and clang 3.4 on OS X cannot harness the generic version of `operator<<`. However, they both succeed in taking advantage of a hand-made, non-generic version defined as follows:

```cpp
std::ostream& operator<<(std::ostream& os, date::sys_seconds const& tp) {
    auto const dp = date::floor<date::days>(tp);
    os << date::year_month_day(dp) << ' ' << date::make_time(tp - dp);
	return os;
}
```

It compiles and behave as expected. What am I doing wrong?

thanks.

**Comment by HowardHinnant** [comment]
Unfortunately you need a `using namespace date` so that ADL can find the streaming operator for the `chrono::time_point` in namespace date.  This is a generic issue with the `std::ostream` library for all types that live in namespace std (i.e. same problem with writing a streaming operator for `pair` or `vector`).

**Comment by iliocatallo** [comment]
Thank you for the clarifications. I did not think about the need for ADL, but it makes perfectly sense now. Let's hope to see these overloads under `std::chrono` some day.
