### ISSUE TITLE
init_tzdb slow in Visual Studio debugger

### ISSUE THREAD

**Issue by damian123** [HowardHinnant/date#93]
When I call init_tzdb in the debugger it takes ~ 1 minute and 13 seconds.
2016-09-28 07:30:33.9777017 Init TZDB...
2016-09-28 07:31:46.2048970 Init TZDB done...

The call to Rule::split_overlaps(db.rules); seems to take all the time.

When I run the same code outside of the debugger (CTRL+F5) it takes 1 sec and 47 milliseconds
2016-09-28 07:26:44.1113231 Init TZDB...
2016-09-28 07:26:45.6855314 Init TZDB done...

In release mode it takes just 69 milliseonds
2016-09-28 07:28:25.3329903 Init TZDB...
2016-09-28 07:28:25.4011985 Init TZDB done...

I am using Visual Studio 2013.
Might just be a VS problem..

**Comment by HowardHinnant** [comment]
Can you confirm that `LAZY_INIT == 1`?  It should be set here:
https://github.com/HowardHinnant/date/blob/master/tz.h#L53-L55

**Comment by damian123** [comment]
Yes, LAZY_INIT ==1 but the slow part is before that in init
I "solved" the problem by delete some of the files in the database.

Is it possible to save down the state of the library in a binary file to help the startup speed?

**Comment by damian123** [comment]
I can confirm that the same issue is in Visual Studio 2005 update 3 when I run it in the debugger.

**Comment by damian123** [comment]
I will work on serializing the state of the database once it has been loaded in a fork

**Comment by ta1meng** [comment]
I had been meaning to report this issue, but have not done so yet because we found a workaround. If you build in Release and ensure the following in the property pages, you should be able to Debug with the approximate performance of Release:

1) C/C++ -> General -> Debug Information Format -> Program Database (/Zi)
2) C/C++ -> Optimization -> Optimization -> Disabled (/Od)
3) Linker -> Debugging -> Generate Debug Infor -> Optimize for debugging (/DEBUG)

I also use Visual Studio 2015 update 3.
